openshift-eng/ocp-qe-perfscale-ci

Jenkinsfile
Taking out hard coding of machine set count of 3 and using all of the machinesets 
https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/2
=> Cluster workers scaling

Jenkinsfile
Had an issue the other day that the counting was off for the number of workers that were created in each of the machinesets
Noticed that there is still one hard set 3 on one line
=> Cluster workers scaling -- Missed one hard set 3 

Jenkinsfile, workload-node-machineset-aws.yaml
Adding in zone a instead of d. This was not working for me on the openshift-qe aws account. Also changing to private security group. Using the public group the workload node never would become running
=> Cluster post config aws region updates

Jenkinsfile
Hit 2 issues with cluster density (see below jobs).
had to add in an option because the python3.8 could get installed in a python3 folder or python3.8 folder
..e2e-benchmarking-multibranch-pipeline/job/cluster-density/259/consoleFull
...paige-e2e-multibranch/job/cluster-density/135/console
=> Cluster density

Jenkinsfile
This adds in the python 3.8 installation that are needed for the ripsaw-cli
=> Adding python3.8 updates for ripsaw-cli

prow/Dockerfile
Prow CI is not finding virtualenv in /root/.local/bin in the image.   Move it to /usr/bin.
=> Move virtualenv to /usr/bin after install

prow/Dockerfile
quay.io/openshifttest/python:3.9 image needs virtualenv installed
=> Need to install virtualenv

prow/Dockerfile
Update image with uuidgen and envsubst commands.  Symlink bash to where e2e-benchmarking expects it.
=> Update image with uuidgen and envsubst commands.  Symlink bash to where e2e-benchmarking expects it.

Jenkinsfile, infra-node-machineset-gcp.yaml, workload-node-machineset-gcp.yaml
Changes in this PR specifically for GCP:
* Fixed all infra machinesets to have cluster name in them 
* Install dir was not able to be found, used env variable (VARIABLES_LOCATION) instead to find type of cloud provider
* Network sometimes was a truncated version of the cluster name was not able to be found
* Similar to network, the subnet could be truncated 
* If just adding the infra nodes portion of this Jenkinsfile, needed to get the correct network
* Added a way to dynamically get the region that the cluster is in
* Service account email did not exist with the name that was shown so infra and workload nodes would fail to create
Fixes: https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/38
=> Fixing names of infra machinesets, network, adding region for GCP

Jenkinsfile
Here JOB and Job type were doing the same thing and had a lot of cases where job and job-type did not match and would write to the wrong sheet. Updates of taking out parameters in workloads coming
=> Taking out job type, duplicate variable

Jenkinsfile
Taking out job type from write to file, goes with PR: https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/41
=> Taking out job type from cluster-density

Jenkinsfile
Remove pip install - no longer necessary due to e2e-benchmark changes
=> Remove pip3 install of requirements.txt - hostnetwork

Jenkinsfile
Adding in master and worker counts to flexy installation. This is helpful for things such as 5 master clusters
=> Adding worker and master node counts for creating flexy 

Jenkinsfile
Requirements were removed from https://github.com/cloud-bulldozer/e2e-benchmarking/tree/master/workloads/network-perf repository.
Missing this file is making jenkins dizzy :)
=> Removing installation of requirements

Jenkinsfile
Currently flexy doesn't support any other alibaba installer type other than fips-ovn-ci, so adding in this specific type for alibaba
=> Adding ovn type for alibaba

Jenkinsfile
For vsphere we need to export certain proxy's. To be able to call the worker scaler on the cluster from within the node density test we need to pass the env-vars set from node-density
=> Adding env vars passing to different jobs

Jenkinsfile
For vsphere we need to export certain proxy's. To be able to call the worker scaler on the cluster from within the cluster density test we need to pass the env-vars set from cluster-density
=> Adding env vars passing to other jobs

Jenkinsfile
When flexy-install was provided by loaded-upgrade build and cluster was marked: DESTROY_WHEN_DONE, then jenkins was running two flexy-destroy jobs. ex. https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/loaded-upgrade/189/console
=> Adding missing condition for flexy-destroy

Jenkinsfile, upgrade_scripts/check_upgrade.py, upgrade_scripts/upgrade.sh
Adding in flag to do Eus upgrade type
Pause the mcp worker 
"oc patch mcp/worker --type merge --patch '{"spec":{"paused":true}}'"
Set the channel to fast-4.<number>
oc adm upgrade --to 4.<number>.<number>
Unpause workers (after all upgrades complete)
oc patch mcp/worker --type merge --patch '{"spec":{"paused":false}}'
Version number must be in the list of recommended paths when callin `oc adm upgrade`
Or will print `Could not find target version 4.<version_num> in 'oc adm upgrade' recommended paths
` and exit
=> EUS upgrade type

Jenkinsfile, README.md, infra-node-machineset-alicloud.yaml, infra-node-machineset-ibmcloud.yaml, workload-node-machineset-alicloud.yaml, workload-node-machineset-ibmcloud.yaml
Adding infra and workload nodes for alibaba cloud.
this will create 2 infra machine sets (1 in zone a and 2 in zone b, because there is no c zone)
Doc I used on how to create machinesets for alibaba: https://deploy-preview-41943--osdocs.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-alibaba.html
Passing run: jenkins.../scale-ci/job/paige-e2e-multibranch/job/cluster-post-config/57/console
Fixes: https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/63
=> Adding alibaba starting for infra or workload nodes

Jenkinsfile
Networking scripts were simplified in e2e-benchmarking.   Match scale-ci to the changes.
=> Update for e2e-benchmarking script changes

Jenkinsfile, README.md
This is adding in calls to scale up and the 2 more new general scale-ci jobs (kube-burner and network-perf). Those 2 pr's need to go in before this one and I'll update the build links 
For etcd-perf and router-perf I took out the passing of scale-up and scale-down so it doesn't scale twice 
I wasn't sure where scale-down fits into this workload. Any ideas? 
NOTE: Wanting to get this initial PR in before adding in a cerberus check as well as getting a must-gather if any failures
=> Scale jobs in loaded-upgrade

Jenkinsfile
Build number isn't getting passed properly to cluster-workers-scaling if you build the cluster from loaded-upgrade
[https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-mu[…]eline/job/loaded-upgrade/285/console](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/loaded-upgrade/285/console)
[https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-mu[…]ster-workers-scaling/554/parameters/](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/cluster-workers-scaling/554/parameters/) (not getting build number)
=> incorrect build string if building cluster

Jenkinsfile
[OCPQE-9178]
(https://issues.redhat.com/browse/OCPQE-9178)
Install Infra and workload nodes on cluster with worker nodes <=50
added the same parameter as of 'pr' https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/101 to kube-burner branch.
positive test case passed:[expected job done]   INFRA_WORKLOAD_INSTALL is checked
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/sninganu-e2e-benchmarking-multibranch-pipeline/job/kube-burner/16/console
negative test case passed  INFRA_WORKLOAD_INSTALL is unchecked
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/sninganu-e2e-benchmarking-multibranch-pipeline/job/kube-burner/17/console
=> Kube burner

.gitignore, Jenkinsfile, write_to_sheet/get_es_data.py, write_to_sheet/get_scale_output.py, write_to_sheet/uperf_find_uuid.json, write_to_sheet/write_helper.py, write_to_sheet/write_scale_results_sheet.py
Previously network-perf and sometimes etcd-perf did not write to the google sheet at all. This adds in printing off of important information for each of those tests as well as parameters from the previous jobs 
In network-perf, printing off the google sheet that gets created 
In etcd-perf, printing off the 99% latency 
https://docs.google.com/spreadsheets/d/1uiKGYQyZ7jxchZRU77lsINpa23HhrFWjphsqGjTD-u4/edit?usp=sharing
These 2 new parameters will also need changes in kube-burner and network-perf as well. Will open those PR's soon and link to this one
=> Adding working print of certain scale results

write_to_sheet/get_es_data.py, write_to_sheet/write_scale_results_sheet.py
Adding in a couple of updates for failure cases of not finding UUID for the run. This will also help with concurrent builds when the benchmark is cleaned up after every application run we will still be able to get the pod_ready informaiton
=> Adding in a backup way to get UUID (helps with concurrent builds)

write_to_sheet/write_scale_results_sheet.py
There are some cases where UUID might be capitalized in the json we get to get uuid for router perf. Adding in return of lower case uuid, upper case and adding in error case option 
Example of failure: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/write-scale-ci-results/830/console
=> Small fix for router perf getting UUID

Jenkinsfile
Adding in ci-profiles cluster build option. This will be an either or option with the drop downs for the cloud type, network type and installation type.  
The OCP_PREFIX and OCP_VERSION will be used by both flexy cluster creation types 
Also added in descriptions to the top level job to easily see what all was run in the job itself
Link to profiles job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/profiles/12/
=> Adding ci profiles option to loaded-upgrade

Jenkinsfile
Need to set proper status based on only the response of the run script not of if "tee" completed properly 
Examples of a job that actually failed but passed overall
[Passed job](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/kube-burner/90/console)
Used this doc: https://stackoverflow.com/questions/6871859/piping-command-output-to-tee-but-also-save-exit-code-of-command
Job now with correct failure status: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-status/3/console
CC: @nathan-weinberg
=> Getting status of python script not tee

Jenkinsfile, README.md
Router-perf job has no check box of INFRA_WORKLOAD_INSTALL yet, add it.
Tested with job:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/qili-e2e-benchmark/job/router-perf/5
Machinesets created after job run:
```
% oc get machinesets -A
NAMESPACE               NAME                                     DESIRED   CURRENT   READY   AVAILABLE   AGE
openshift-machine-api   infra-us-east-2a                         1         1         1       1           22m
openshift-machine-api   infra-us-east-2b                         1         1         1       1           22m
openshift-machine-api   infra-us-east-2c                         1         1         1       1           22m
openshift-machine-api   qili-41011-aws-ntxmx-worker-us-east-2a   40        40 …
```
=> add INFRA_WORKLOAD_INSTALL to router-perf

write_to_sheet/get_es_data.py, write_to_sheet/write_helper.py, write_to_sheet/write_scale_results_sheet.py
Currently when the kube-burner tests finish it cleans up the benchmark-operator namespace and all objects that I was using to get the pod ready latencies. I have added in back up ways to get the UUID from the output but now need to pass it to be able to get the pod latencies of the job properly
I created a PR to only cleanup the namespace if you want to cleanup all the objects as well
https://github.com/cloud-bulldozer/e2e-benchmarking/pull/381
=> Adding getting pod averages in error cases

Jenkinsfile
Adding propogate false for write to file job to not have write to file affect final result of kube-burner job
=> Propagate false for write to file

Jenkinsfile
Adding propogate false to network-perf write to sheet to not have the pass/fail status of write to sheet effect the overall network-perf test status
=> Propogate false for write to sheet in network perf

Jenkinsfile, README.md, cleanup.py
Resolves OCPQE-9127
Adding cleanup script for CI usage. Takes in the workload type to be able to delete namespace that were created during the kube-burner run. Also have the option to delete benchmark-operator namespace and objects if they exist
Example: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cleanup/69/console
=> Adding cleanup script for specific jobs

Jenkinsfile, OWNERS, README.md
This job separates out the flexy cluster installation from loaded-upgrades. This helps be able to use flexy installation based on the scale-ci profiles to be used in loaded-upgrades but also any nightly cron jobs 
Will be opening additional PR to use this job in loaded-upgrades with this branch: https://github.com/paigerube14/ocp-qe-perfscale-ci/tree/call_install
=> Install helper 

Jenkinsfile
Adding propogate false for write to file job to not have write to file affect final result of router-perf job.
Similar to https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/116
=> Propagate false for write to file - router-perf

Jenkinsfile, scripts/README.md, scripts/cluster-monitoring-config.yaml, scripts/common.sh, scripts/flows_v1alpha1_flowcollector_versioned.yaml, scripts/loki-storage-1.yaml, scripts/loki-storage-2.yaml, scripts/netobserv-metrics.yaml, scripts/netobserv.sh, scripts/noo-subscription.yaml, scripts/operator_group.yaml, scripts/run_workloads.sh, scripts/service-monitor.yaml
https://issues.redhat.com/browse/NETOBSERV-332
* Adding manifests for ServiceMonitor and ConfigMap  to send NO metrics to cluster prometheus 
* updating scripts to apply ServiceMonitor and ConfigMap manifests 
* Adding NO metrics file for kube-burner workload * updating Jenkinsfile to have python 3.9.12
* thanos URL and user workload secrets instead of prometheus for user workload metrics.
*  Create operator group
* Ability to deploy NOO from OperatorHub or from main branch
Note that: For this to work successfully, it is dependent on to get the correct token that's done by changes added to [forked e2e-benchmarking repo](https://github.com/memodi/e2e-benchmarking/blob/netobserv-trials/workloads/kube-burner/common.sh#L15-L20)
Test run from jenkins: …
=> Netobserv 332

Jenkinsfile
$title
Please check issue https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/145 for more information.
=> Getting machineset using additional label flag to ignore 'infra' nodes.

Jenkinsfile
Adding missing description for building cluster. Sharada had also noticed that the profile size was not being passed from loaded-upgrade to cluster-builder 
Gave incorrect version but wanted to verify profile got put in description and size got properly passed to cluster-builder (which it did)
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/loaded-upgrade/302/
=> Adding description and passing profile size to cluster-builder

Jenkinsfile, README.md, infra-node-machineset-alicloud.yaml, infra-node-machineset-aws.yaml, infra-node-machineset-azure.yaml, infra-node-machineset-gcp.yaml, infra-node-machineset-ibmcloud.yaml, infra-node-machineset-vsphere.yaml, workload-node-machineset-alicloud.yaml, workload-node-machineset-aws.yaml, workload-node-machineset-azure.yaml, workload-node-machineset-gcp.yaml, workload-node-machineset-vsphere.yaml
Fix https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/148 and https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/153
Summary of changes:
1. Fix hard code of location on azure
2. Update the storage class of Azure to the default storageclass `managed-csi`
3. Add comment to README that Azure only support `region: centralus`
4. Add cluster name to machiesets name as prefix for all providers, this will help to identify owner of resources.
5. add infra and workload label to metadata of GCP machinesets https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/153
=> Fix Azure and GCP INFRA WORKLOAD configuration related issues

Jenkinsfile, README.md
Adding more detailed information about the variables to pass for CI_profiles/installation in general
This is also fixing an issue where the scale-ci test would not run because of incorrectly setting a top level variable
=> Adding install help information to readme and comment

README.md, write_to_sheet/get_es_data.py, write_to_sheet/write_helper.py, write_to_sheet/write_loaded_results.py, write_to_sheet/write_nightly_results.py, write_to_sheet/write_scale_results_sheet.py
Updating getting uuid and pod latencies timing by using creation time in the job output parameter passed. 
Fixes writing out for network-perf and concurrent-builds
=> Adding getting pod averages in error cases by time in job output

Jenkinsfile
Currently infra scale up for ibmcloud provider is not setup in
https://issues.redhat.com/browse/OCPQE-10249
https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/cluster-workers-scaling/
add if statement for ibmcloud in https://github.com/openshift-qe/ocp-qe-perfscale-ci/tree/cluster-workers-scaling
to pass the parameters listed here
https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/d7cfdac2e05dbd98f894a14cc048580f0b2a4b01/Jenkinsfile#L84
Case1:  check the INFRA_WORKLOAD_INSTALL with workers=40; cluster-post-config should be triggered; test success ; https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/sninganu-e2e-benchmarking-multibranch-pipeline/job/cluster-workers-scaling/17/console
Case2:  uncheck the INFRA_WORKLOAD_INSTALL with …
=> To scale up and down the clusters by changing machinesets replicas count for worker nodes on ibmcloud

Jenkinsfile
Forgot that we changed the name of the repository cerberus is in and switch master to main. Had git pulling issues with old branch/url on jenkins
=> Main branch and repo url for cerberus

Jenkinsfile, README.md
As part of [PR](https://github.com/cloud-bulldozer/e2e-benchmarking/pull/393) we added the ability to get benchmark-comparison google sheet output from kube-burner workloads. Need to add setting of comparison_config, google sheet service account and email to send it to 
This only works on jenkins agents that start with "oc4*" for now. Still trying to fix for rhel8 agents
=> Adding in user email and comparison config for kube-burner

Jenkinsfile, infra-node-machineset-osp.yaml, workload-node-machineset-osp.yaml
Adding in infra and workload node templates for OSP 
This incorporates the changes that were in https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/163 into this one so I was able to fully test this addition
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cluster-post-config/69/console
=> Adding osp with templates for infra and workload nodes

scripts/NetObserv_ebpf_Metrics.json, scripts/README.md, scripts/analyze_metrics.py, scripts/netobserv-ebpf-metrics.yaml, scripts/nope.py, scripts/requirements.txt
1. Adding metrics and dashboard for ebpf agent.
2. Adding analyze script as an interim way to get some statistics easily in absence of ES uploads. Script runs on top the JSON file that nope.py tool outputs it can be simply run as: `./analyze_metrics.py <path to json file>`
3. fix in nope.py to just get `new-token` anyway instead of `get-token` so we don't run into errors.
=> updates for ebpf, metrics analyze script and fixes

Jenkinsfile, write_to_sheet/write_loaded_results.py, write_to_sheet/write_nightly_results.py, write_to_sheet/write_scale_results_sheet.py, write_to_sheet/write_to_sheet.py
Printing off more data of cluster type/configuration when running scale-ci tests 
For ticket: https://issues.redhat.com/browse/OCPQE-10834
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write-helper/5/
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write-helper/4/
=> Adding extra data to google sheet matrix

Jenkinsfile
On a hybrid cluster, I scaled CoreOS machineset to 38 workers, but the code get 75 workers because I have 37 RHEL workers installed on the cluster.
The code compare 38(expected) and 75, it doesn't match, so the loop will continue to check until max attempt is reached.
```
% oc get nodes --no-headers -l node-role.kubernetes.io/worker | grep -v "NotReady\\|SchedulingDisabled" | grep worker -c
75
% oc get nodes --no-headers -l node-role.kubernetes.io/worker -o wide| grep CoreOS | grep -v "NotReady\\|SchedulingDisabled" | grep worker -c
38
```
=> Only check the CoreOS worker

Jenkinsfile
Was getting error seen below if the checks passed, fixing to check if cerberus passes first 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/cerberus/98/console
```
07-12 10:21:05.794  Archiving artifacts
07-12 10:21:05.831  ‘inspect_data/*’ doesn’t match anything, but ‘*’ does. Perhaps that’s what you mean?
07-12 10:21:05.836  [Pipeline] }
07-12 10:21:05.840  [Pipeline] // script
07-12 10:21:05.843  [Pipeline] }
07-12 10:21:05.846  [Pipeline] // withEnv
07-12 10:21:05.886  [Pipeline] }
07-12 10:21:05.894  [Pipeline] // node
07-12 10:21:05.897  [Pipeline] }
07-12 10:21:05.900  [Pipeline] // stage
07-12 10:21:05.904  [Pipeline] End of Pipeline
07-12 10:21:05.914  ERROR: No artifacts found that match the …
```
=> Adding cerberus fix for inspect data folder

infra-node-machineset-azure-customervpc.yaml, workload-node-machineset-azure-customervpc.yaml
Still have image pull failure from quay, I did some additional fix.
Record a worker machineset yaml for reference:
```
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
annotations:
machine.openshift.io/GPU: "0"
machine.openshift.io/memoryMb: "32768"
machine.openshift.io/vCPU: "8"
creationTimestamp: "2022-07-20T01:33:22Z"
generation: 2
labels:
machine.openshift.io/cluster-api-cluster: qili-az-p0720-pgpsp
machine.openshift.io/cluster-api-machine-role: worker
machine.openshift.io/cluster-api-machine-type: worker
name: qili-az-p0720-pgpsp-worker-centralus1
namespace: openshift-machine-api
resourceVersion: "275948"
uid: a927012f-5623-4f0f-929c-3d74d4bed338
spec:
replicas: 25
selector:
matchLabels:
machine.openshift.io/cluster-api-cluster: qili-az-p0720-pgpsp …
```
=> Azure private infra and workload machineset yaml fix image pull failure from quay

Jenkinsfile
Made changes to return a non-zero exit in case of failures from the script.
Test run--- Verified!
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/sninganu-e2e-benchmarking-multibranch-pipeline/job/network-perf/13/console
=> to catch failure condition

Jenkinsfile
Fixing: 
* Adding params for cerberus and cleanup to pass to sub jobs
* Adding in file check for earlier release that don't have _flexy-artifacts/workdir/install-dir/cluster_info.yaml_ file 
* Spacing out parameters
=> Adding check if file types exist and cerberus cleanup params

Jenkinsfile
Adding in setting CERBERUS_CORES based on the number of projects 
During execution of checking the cluster status with over 150 projects on the cluster the agent is becoming disconnected because the cores are getting overloaded 
This is currently always failing when running cluster-density tests with over 100 iterations (applicable when doing medium scale testing)
=> Adding cerberus core

Jenkinsfile
Don't want hardcoded 4.10 folder when looking at profiles as there are different profiles now in each of the versioned folders
Job now with properly getting profile in 4.12 folder: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/loaded-upgrade/340/console
[failing job](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/loaded-upgrade/632/) with original issue
=> minor and major version for profile folder

Jenkinsfile
Lowering the cerberus cores because almost all jobs (no matter the project count) are still aborting from time to time
=> jenkins jobs are still aborting sometimes in cerberus

scripts/nope.py
tested nope.py locally:
```
$ python nope.py --starttime 1662738423 --endtime 1662738838 --jenkins-job scale-ci/e2e-benchmarking-multibranch-pipeline/kube-burner --jenkins-build 1227 --uuid 1dc028ad-ff3d-48fb-bb23-7876760eeb35 --user-workloads --dump
INFO:root:Parsed Start Time: 11:47AM UTC on 09/09/2022
INFO:root:Parsed End Time:   11:53AM UTC on 09/09/2022
INFO:root:Step is:           10
INFO:root:Associating run with Jenkins job scale-ci/e2e-benchmarking-multibranch-pipeline/kube-burner build number 1227
INFO:root:UUID: 1dc028ad-ff3d-48fb-bb23-7876760eeb35
INFO:root:YAML_FILE: netobserv_queries_ebpf.yaml
INFO:root:THANOS_URL: https://thanos-querier-openshift-monitoring.apps.nweinber-ebpf1.qe.devcluster.openshift.com
INFO:root:TOKEN: …
```
=> updates for PR # 256

scripts/netobserv_queries_ebpf.yaml, scripts/netobserv_queries_ipfix.yaml
this would enable us to view resources and enable us to derive 1:1 correlation between flows and resources consumed by pod.
( this was discussed as action item during 09/12 NO QE Sync meeting)
Queries tested locally:
```
$ cat test_query.yaml
- query: pod:container_cpu_usage:sum{namespace="network-observability"} * on (pod) group_left(node) kube_pod_info{namespace="network-observability"}
metricName: cpuUsage
- query: pod:container_cpu_usage:sum{namespace="network-observability-privileged"} * on (pod) group_left(node) kube_pod_info{namespace="network-observability-privileged"}
metricName: ebpfCpuUsage
- query: sum(rate(ingest_collector_flow_logs_processed[1m])*60) by (pod) * on (pod) group_left(node) kube_pod_info{namespace="network-observability"}
metricName: nFlowLogsProcessed
$ …
```
=> Adding node name label for metrics

Jenkinsfile
Solving problem with loaded large clusters.
https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/194
Successful run: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/skordas-e2e-bmp/job/cleaning-before-scaling/2/console
=> Moving cleaning cluster before scaling down the cluster.

scripts/lokistack-1x-exsmall.yaml, scripts/lokistack-1x-medium.yaml, scripts/lokistack-1x-small.yaml, scripts/netobserv.sh, scripts/netobserv_queries_ebpf.yaml, scripts/netobserv_queries_ipfix.yaml
Resolves https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/260 partially
/cc @nathan-weinberg @mffiedler
=> update loki manifests to use cluster default SC

Jenkinsfile, install_infra_work.sh
Monitoring pods were not going ready/running because they made reference to a storage class that did not exist on the cluster. 
I added in a way to verify if the storage class existed on the cluster and if not set the prometheus/monitoring storage class to be the default storage class found in the cluster
There was also an issue that we never fully checked that the monitoring pods were running before marking the job successful. I added in code to make sure the statefulset that creates the pods has 2 replicas and the 2 running monitoring pods are on the infra nodes
Not setting new storage class and still successful 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/default_storage_class/14/consoleFull
Successful job of …
=> Default storage class 

Jenkinsfile, check_kube_burner_ns.py, set_namespace_list.py
When there are too many pod in namespace, cerberus in jenkins doesn't have enough computer power or memory to finish the cerberus run on those pods. If all namespaces are given, we are going to remove the namespace that matches the workload type 
Doing a separate check at the end to see if any of the pods are not running and getting their logs
See it in action here https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cerberus/281/
Note: the kube burner job itself will also fail if any of the pods go not ready. We are really wanting to check in this case if any of the cluster components are failing
=> Taking out check of workload projects

cleanup.py
If the user doesn't pass a workload it'll delete all namespaces that have the label "kube-burner-job" but doesn't matter what the workload type is. This will be very useful for all the custom workloads we are adding to regression-test type
Example: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/benchmark-cleaner/19/console
=> Adding blank option to cleanup 

Jenkinsfile
Adding workload type to cerberus passing 
Also need to add extra pip requirements for concurrent builds
=> Kube burner cerberus

scripts/nope.py
We need to make some ES schema changes for the long-lived Grafana dash - this PR ensures our tooling (specifically NOPE) will be compatible with those changes.
=> Changes to match updated ES schema

Jenkinsfile
With [PR](https://github.com/cloud-bulldozer/e2e-benchmarking/pull/411#event-7495808244) we decided to move to using container CPU and container memory because those metrics were already being captured. So we now need to update the csv generator with that data instead of pods
=> Updating metrics to generate

Jenkinsfile
Get all stdout from new kube-burner sub run to pass to write to scale properly
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner/97/console
Can see that all the output gets to the JOB_OUTPUT variable here: 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/write-scale-ci-results/3057/parameters/
vs. 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/write-scale-ci-results/3032/parameters/
Missing kube burner output
=> Printing all output to file

Jenkinsfile
Get all output from runs: similar to router-perf and kube-burner updates
https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/286
=> Get all output in output file 

scripts/sandman.py
https://github.com/cloud-bulldozer/e2e-benchmarking/pull/475 broke Mr. Sandman due to changes in how `.out` files are generated - this PR addresses this regression
File: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner/97/artifact/workloads/kube-burner/kube-burner.out/*view*/
Sandman:
```bash
[nathan@nathan-redhat ocp-qe-perfscale-ci (sandman)]$ ./scripts/sandman.py --file kube-burner.out
uuid: 773bc169-4368-4f66-869b-2ceeb97c9cd8
starttime_string: 2022-10-05 15:21:05
endtime_string: 2022-10-05 15:26:17
starttime_timestamp: 1664983265
endtime_timestamp: 1664983577
```
File: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/router-p …
=> Fixed Mr. Sandman

write_to_sheet/write_scale_results_sheet.py
Getting uuid from namespaces created labels because there are no benchmark objects 
Need new way to get time of start of run
successful run: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write-scale-ci-results/140/console
=> Write scale ci results with no benchmark-operator

Jenkinsfile
Adding specific jenkins pod information to be able to have enough resources to run kube-burner console
Needed to add multiple stages to not use the same pod in kube-burner as passing to others or get out of memory in sub jobs
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner/106/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/benchmark-cleaner/454/console
Successful main part of job with sub jobs with agents properly passed: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner/110/console
https://issues.redhat.com/browse/OCPQE-12434
=> Kube burner cpu/memory limit

Jenkinsfile, scripts/flows_v1alpha1_flowcollector_lokistack.yaml, scripts/flows_v1alpha1_flowcollector_versioned_lokistack.yaml, scripts/netobserv.sh
1. re-order Kafka steps to prevent from running into issue [NETOBSERV-575](https://issues.redhat.com/browse/NETOBSERV-575)
2. NETOBSERV-660 changed metrics section.
cc @nathan-weinberg - minor changes IMO, please review and let me know if you need success run.
=> changes for NETOBSERV-660 and re-ordering Kafka steps.

write_to_sheet/write_helper.py, write_to_sheet/write_scale_results_sheet.py
Missing env_vars_file when writing results to sheet
Results of runs can be seen in the cluster-density tab
no results were being written for kube-burner type jobs
=> Write scale ci results

infra-node-machineset-azure-customervpc.yaml, infra-node-machineset-azure.yaml, install_infra_work.sh, workload-node-machineset-azure-customervpc.yaml, workload-node-machineset-azure.yaml
Issue: https://issues.redhat.com/browse/OCPQE-12540
Tested with 4.11:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Flexy-install/148718/
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/skordas-e2e-bmp/job/cluster-post-config-412azure/2/console
and 4.12:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Flexy-install/148722/
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/skordas-e2e-bmp/job/cluster-post-config-412azure/3/console
^^ jobs are failing due statefulset-controller issue - but infra nodes are provisioned correcttly.
=> Getting resourceID from existing machineset.

scripts/nope.py
Implementation was actually suppressing `DEBUG` level logging - this PR fixes that. Tested here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/223/console
=> Fixed small bug with colored logging

Jenkinsfile, scripts/README.md, scripts/deploy-loki-aws-secret.sh, scripts/flows_v1alpha1_flowcollector_lokistack.yaml, scripts/flows_v1alpha1_flowcollector_versioned_lokistack.yaml, scripts/netobserv.sh, scripts/nope.py, scripts/uperf_env.sh
This PR makes the following changes:
- Simplifies Jenkinsfile with additional template directions and scripting moved to the shell scripts
- Removed need for `$WORKSPACE` variable if running `netobserv.sh` scripts locally
- Updated shell scripts with additional logging and minor functionality changes
- Added `nukeobserv` function to completely remove all NetObserv artifacts from a cluster
- Updated CRDs by changing `cacheMaxFlows` value for eBFP
- `uninstall_netobserv` no longer requires `INSTALLATION_SOURCE` to be set
- Switched `Setup FLP service and service-monitor` and `Configure flowcollector and Kafka` Jenkins stage positions and names
- Minor fix to NOPE tool
=> Updated Jenkinsfile and shell scripts, some CRD configs

Jenkinsfile, README.md
Adding job to be able to run cerberus, kraken and an upgrade in parallel 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/chaos_upgrade/41/console 
(failure only because I had to abort Cerberus b/c I gave too many iterations) 
Currently have to hard code number of iterations for cerberus to run. Each iteration (with the 3 second wait) takes between 7-10 seconds and an upgrade takes any where from 1.2 -3 hours. 
Note: For an upgrade that latest 1.2 hours I ran about 500 iterations in the same time
=> Adding parallel runs of kraken,cerberus,upgrade(if set)

Jenkinsfile
Adding QE es server set up to kube-burner job to keep our own history 
Need to update write to script to properly get new grafana link 
Passing job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner/168/console
https://search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'0af29050-07fa-11ec-97a8-03ce3777b5a2',key:uuid,negate:!f,params:(query:a3b8dc37-6675-42f9-9e3b-885b3da3ba6c),type:phrase),query:(match_phrase:(uuid:a3b8dc37-6675-42f9-9e3b-885b3da3ba6c)))),index:'0af29050-07fa-11e …
=> Kube burner with QE es server

Jenkinsfile, write_to_sheet/get_es_data.py, write_to_sheet/write_helper.py, write_to_sheet/write_scale_results_sheet.py
With the switch to the new qe elastic server, we were not properly curling the right server when printing the results to the google sheet. 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/qe_es_grafana/10/console
See cluster density with "test" and 4 parameters with pod latencies
=> adding pod latencies to new es server

Jenkinsfile
https://issues.redhat.com/browse/OCPQE-13657
Issues
1. VARIABLE Description is not correct
pod-density-heavy: This will export PODS env variable; set to 200 * num_workers, work up to 250 * num_workers. Creates as many "sleep" pods as configured in this environment variable.
2.
pod-density-heavy uses 'PODS_PER_NODE'
https://github.com/cloud-bulldozer/e2e-benchmarking/blob/ceda3aa90601c35813166694dfe167d954fa941a/workloads/kube-burner/run.sh#L59 set PODS_PER_NODE=${PODS_PER_NODE:-245}
=> fix for pod-density-heavy

Jenkinsfile, README.md, upgrade_scripts/check_upgrade.py, upgrade_scripts/upgrade.sh
When trying to upgrade to 4.12 with EUS type, got an error only on the console giving documentation link: https://access.redhat.com/articles/6955381
Adding the command in the documentation when doing 4.11->4.12 upgrades 
After pr gets merged, wanting to take advantage of the new must gather job for collecting data about a cluster
https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/353/files
=> Upgrade updates for EUS and 4.12

prow/Dockerfile
Adding jq option on system for OCP-QE-Perfscale tests in prow 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/36227/rehearse-36227-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-ocp-qe-perfscale-ci-tests/1623714904819109888
```
time="2023-02-09 18:08:27" level=info msg="Finished the create job in 1h0m35s"
time="2023-02-09 18:08:27" level=info msg="Verifying created objects"
time="2023-02-09 18:08:27" level=info msg="pods found: 674 Expected: 674"
time="2023-02-09 18:08:27" level=info msg="Stopping measurement: podLatency"
time="2023-02-09 18:08:27" level=info msg="Evaluating latency thresholds"
time="2023-02-09 18:08:27" level=error msg="❗ P99 Ready latency (965.74s) higher than configured threshold: 2m0s"
time="2023-02-09 18:08:29" level=info …
```
=> Adding jq instllation for pypi and aptget

Jenkinsfile
After pr: https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/374 we will want to add this option at top level
=> Adding churn option for kube-burner at top level

Jenkinsfile, OWNERS, README.md
Adding kube-burner ocp type of running kube burner tests. They use the files that are preconfigured at https://github.com/cloud-bulldozer/kube-burner/tree/master/cmd/kube-burner/ocp-config
Running job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner-ocp/12/
=> Adding kube burner ocp run type

Jenkinsfile, scripts/README.md, scripts/catalogsources/qe-unreleased-catalogsource.yaml, scripts/env.sh, scripts/netobserv.sh, scripts/subscriptions/netobserv-operatorhub-subscription.yaml
Changes made:
- Made `CERBERUS_CHECK` optional for increased flexibility
- Explicitly set `MUST_GATHER` to run in the event of a Cerberus failure
- Added NetObserv version info to Jenkins build desc
- Added additional logging around infra and workload nodes
- Switched unreleased catalogsource to use `aosqe-index` image instead of `ocp4-latest`
- Fixed bug where `nukeobserv` would fail if a `NAMESPACE` var wasn't able to be parsed
- Fixed bug where `nukeobserv` didn't delete `qe-unreleased-testing` CatalogSource
- Removed  `env.sh` file and moved functionality to `netobserv.sh`
- Updated `OperatorHub` subscription channel
=> Updated automation scripts and custom CRDs

install_infra_work.sh, mcp-infra.yaml, mcp-workload.yaml
After removing the default `worker` role from the `infra, workload` node, we should add the related `MCP` for them. Otherwise, it will lead to some configs cannot be applied. Details: https://issues.redhat.com/browse/OCPBUGS-10596
=> add infra, workload MCPs

Jenkinsfile, scripts/netobserv.sh
tested locally 
```bash
[nathan@nathan-redhat ocp]$ cat temp.sh 
echo "====> Generate S3_BUCKETNAME"
RAND_SUFFIX=$(tr </dev/urandom -dc 'a-z0-9' | fold -w 12 | head -n 1 || true)
if [[ $WORKLOAD == "None" ]] || [[ -z $WORKLOAD ]]; then
export S3_BUCKETNAME="netobserv-ocpqe-$USER-$RAND_SUFFIX"
else
export S3_BUCKETNAME="netobserv-ocpqe-$USER-$WORKLOAD-$RAND_SUFFIX"
fi
echo $S3_BUCKETNAME
[nathan@nathan-redhat ocp]$ ./temp.sh 
====> Generate S3_BUCKETNAME
netobserv-ocpqe-nathan-6t66njkdcn7f
```
and also Jenkins
```bash
03-22 14:41:38.786  + echo '====> Generate S3_BUCKETNAME'
03-22 14:41:38.786  ====> Generate S3_BUCKETNAME
03-22 14:41:38.786  ++ tr -dc a-z0-9
03-22 14:41:38.786  ++ fold -w 12
03-22 14:41:38.786  ++ head -n 1
03-22 14:41:38.786  + RAND_SUFFIX=hbovazxwn6l2
03-22 14:41:38.786 …
```
=> Added user ID to AWS bucket name generation

upgrade_scripts/upgrade.sh
Update upgrade.sh to support multi-arch ocp upgrade, the sha256 of playload have issue in https://multi.ocp.releases.ci.openshift.org/graph, so need to get PullSpec in webpage as workaround when upgrading OCP using nightly version. 
It's hard to automatically detect if the OCP  is multi-arch like as arm and x86, so need to specify arch type when you plan to upgrade multi-arch OCP 
The Jenkins Logs:
Upgrade multi-arch to nightly version:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/liqcui-e2e-benchmarking-multibranch-pipeline/job/loaded-upgrade/64/ 
Upgrade multi-arch to stable version:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/liqcui-e2e-benchmarking-multibranch-pipeline/job/loaded-upgrade/65/
=> Update upgrade.sh to support multi-arch ocp upgrade

Jenkinsfile
To upgrade multi-arch OCP, It's hard to automatically detect if the OCP is multi-arch like as arm and x86, so need to specify arch type when you plan to upgrade multi-arch OCP
The Jenkins Logs:
Upgrade multi-arch to nightly version:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/liqcui-e2e-benchmarking-multibranch-pipeline/job/loaded-upgrade/64/
Upgrade multi-arch to stable version:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/liqcui-e2e-benchmarking-multibranch-pipeline/job/loaded-upgrade/65/
=> Update Jenkinsfile to support mulit-arch ocp

Jenkinsfile, helper_uuid.py, post_uuid_to_es.py
Adding new option to be able to upload to baselines when none exists for certain configurations, this is off by default but would be helpful for new configurations
Won't upload if data for certain configuration is already out there: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/post-results-to-es/13/console
Post new baseline if none exists: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/post-results-to-es/10/console
=> adding baseline option

Jenkinsfile
After [Pr](https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/408), need to update calls with new variables
Needed to reorder the print to sheet to be able to use the tooling Nathan made in the artifacts files to find the UUID
=> Router perf - new write variables

Jenkinsfile
Adding kube-burner ocp version of workloads with boolean
kube burner ocp version: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/loaded-upgrade/376/console
=> Loaded upgrade - kube-burner-ocp

Jenkinsfile
Adding image optional option and image stream variable
Passing option: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/must-gather/29/
@nathan-weinberg don't know if you want to try the netobserv option on your pre-built cluster to verify that option works
=> Must gather with image options

Jenkinsfile
Want to add kube burner ocp specific file to be able to properly get the data from it in sandman
Needs to go in alongside: https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/439
=> Adding ocp specific output file

scripts/sandman.py
Adding workload type to workload_data and number of iterations if they exist
Router perf: {'workload_type': 'router-perf', 'starttime_string': 'May 29 14:13:39 UTC 2023', 'endtime_string': 'May 29 14:44:16 UTC 2023', 'starttime_timestamp': '1685369619', 'endtime_timestamp': '1685371456', 'uuid': '5849d764-1bec-4f4b-a397-687b0f286b6a'}
Kube-burner-ocp: {'workload_type': 'cluster-density-v2', 'starttime_string': '2023-05-25 21:45:37', 'endtime_string': '2023-05-25 22:01:49', 'starttime_timestamp': '1685051137', 'endtime_timestamp': '1685052109', 'uuid': '13a1f64b-68c4-4def-ac6c-25014d21140c', 'iteratons': '180'}
=> Adding workloads and iterations

scripts/netobserv/flows_v1beta1_flowcollector.yaml
As discussed on Slack, it turns out there are some performance overheads around having profile porting enabled for eBPF and FLP in our FlowCollector CRD. Disabling having those enabled by default - we will introduce Jenkins and Shell scripting options to allow these to be enabled by users if they are needed.
=> Removed all profile porting in FlowCollector

Jenkinsfile, post_uuid_to_es.py
Missing more workload types that are available in kube-burner and kube-burner-ocp
Want to also be able to get the workload type for network perf in the results post to es
=> Adding more workload type and get data for network-perf type

Jenkinsfile
The variable to cleanup the resources or not in the kube-burner ocp version is called GC. Going to leave the upper variable because it is passed and used in other places as well 
https://github.com/cloud-bulldozer/e2e-benchmarking/blob/2ecfb160cf8e57fac8a8c4c366893a02e40af0af/workloads/kube-burner-ocp-wrapper/run.sh#L12
=> adding cleanup variable for kube-burner

scripts/sandman.py
In some of the newer network-perf-v2 tests there is a print off of a UUID. Want to be able to get that uuid if it exists. Does not exist in all output files of network-perf-v2. The except will hopefully catch these cases but we wont want to do anything
See output file here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/network-perf-v2/33/
I had 3 versions of output files and these are the results of running these edits here
```
% python scripts/sandman.py --file network-perf-v2-new.out
starttime_string: 2023-07-07 08:48:15
endtime_string: 2023-07-07 10:15:51
starttime_timestamp: 1688719695
endtime_timestamp: 1688724951
uuid: b57e9a5a-ec41-413d-a045-c09b29500f0f
% python scripts/sandman.py --file …
```
=> Adding find uuid for network perf v2

Jenkinsfile, openshift-qe-move-pods-infra-commands.sh, openshift-qe-workers-infra-workload-commands.sh
To support vsphere8,  we can use the same script of prow ci to add infra/workload and move monitoring/registry/ingress pods script. 
We don't remove old script, just adding new script. 
The Jenkins job is https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/liqcui-e2e-benchmarking-multibranch-pipeline/job/cluster-post-config/195/console
=> update prow ci add infra/workload and move pods script to replace old script

scripts/sandman.py
Want to be able to get uuid, start and end times using sandman script for new ingress perf test 
Used output from this run: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/ingress-perf/5/
```
starttime_string: 2023-07-21 16:37:26
endtime_string: 2023-07-21 17:45:06
starttime_timestamp: 1689957446
endtime_timestamp: 1689961506
uuid: a682b97e-53ff-44c2-a4bd-8bc4a320a290
```
=> Adding ingress perf sandman get uuid

Jenkinsfile
Changes in PR https://github.com/cloud-bulldozer/e2e-benchmarking/pull/590/ breaks perf-comparison in netobserv-perf-tests pipeline. This PR fixes it.
I am currently testing this change.
cc @Amoghrd @nathan-weinberg
=> fix for e2e-benchmarking PR #590

Jenkinsfile
Don't have jq installed in jenkins system by default, installing jq with pip 
```
08-09 10:29:45.149  jq: error (at <stdin>:1): Cannot iterate over null (null)
08-09 10:29:45.149  + grep 'Benchmark comparison failed' ingress_router.out
08-09 10:29:45.154  [Pipeline] archiveArtifacts
08-09 10:29:45.157  Archiving artifacts
08-09 10:29:45.167  Recording fingerprints
```
Job that got past that step: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/router-perf/39/console
=> Router perf no jq

Jenkinsfile
The latest kube-burner version that is set in e2e-benchmarking does not support the current config files that are in e2e-benchmarking/workloads/kube-burner 
Need to hard set the specific version of kube-burner that still works 
Used in conjunction with pr in https://github.com/cloud-bulldozer/e2e-benchmarking/pull/609
Passing job https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner/253/console
=> Kube burner hard coded version

scripts/README.md, scripts/loki/lokistack-1x-exsmall.yaml, scripts/loki/lokistack-1x-medium.yaml, scripts/loki/lokistack-1x-small.yaml
[NETOBSERV-717](https://issues.redhat.com/browse/NETOBSERV-717) adds new LokiStack config options that we want to take advantage of for our performance testing.
Also updating the README with the new changes to the NOPE tool.
=> Updated README and LokiStack CRDs with new stream limits config

Jenkinsfile
Missing jq to be able to iterate in e2e-benchmarking
Error: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/kube-burner-ocp/108/console
```
08-14 12:30:54.148  + ./run.sh
08-14 12:30:54.148  + tee kube-burner-ocp.out
08-14 12:30:54.148  jq: error (at <stdin>:1): Cannot iterate over null (null)
```
=> Adding jq as install

Jenkinsfile, openshift-qe-workers-infra-workload-commands.sh
Adding options for moving pods to infra nodes in cluster post config and support multi-arch
The Jenkins Logs:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/liqcui-e2e-benchmarking-multibranch-pipeline/job/cluster-post-config/223/console
=> Adding options for moving pods to infra nodes in cluster post config

Jenkinsfile
All checked: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/qili-e2e-benchmark/job/cluster-workers-scaling/12/
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/cluster-post-config/1515/parameters/
All un-checked: 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/qili-e2e-benchmark/job/cluster-workers-scaling/13/parameters/
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/cluster-post-config/1518/parameters/
cluster-post-config jobs failed because the cluster already have infra nodes installed, but the tests jobs all have the parameters …
=> add parameters to move infra monitoring and registry

Jenkinsfile
taking out cleanup section as if the cleanpu parameter is set it will auto clean up in the workload itself
in this job the cleanup is done in the workload so there are no namespace when benchmark-cleaner gets called: 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/kube-burner-ocp/155/console
=> taking out duplicate cleanup

upgrade_scripts/check-rosa-upgrade.sh, upgrade_scripts/check_upgrade.py, upgrade_scripts/common.sh
Update code to add correct version to check-version  and increase the timeout of checking mcp and also capture mcp state if mcp isn't readay. 
Prow CI logs
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/41663/rehearse-41663-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-candidate-4.13-loaded-upgrade-from-4.12-perfscale-rosa-multiaz-24nodes-stage-loaded-upgrade413/1693813462578237440/artifacts/perfscale-rosa-multiaz-24nodes-stage-loaded-upgrade413/openshift-qe-rosa-upgrade-postcheck/build-log.txt
Jenkins Job Logs:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/liqcui-e2e-benchmarking-multibranch-pipeline/job/upgrade/97/console
=> update code to check-rosa-upgrade

Jenkinsfile
Adding in infra node check because ingress perf requires it
No infra nodes: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/ingress-perf/10/console
infra nodes on cluster -> started to run test: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/ingress-perf/11/console
=> Ingress perf infra check

openshift-qe-move-pods-infra-commands.sh
In previous versions the "--duration" was not an option in the `oc create` command. Need to other command options for older versions 
Can see this command in use: https://github.com/cloud-bulldozer/e2e-benchmarking/blob/f7641e36cc07271205be4cc7e15b0c2097a1f7ac/workloads/network-perf/common.sh#L13
https://issues.redhat.com/browse/OCPQE-16652
=> Duration not an option in older (4.10) version

Jenkinsfile
Setting specific kube burner version to try to get around issue: https://github.com/cloud-bulldozer/e2e-benchmarking/issues/619
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner-ocp/83/console
=> Kube burner ocp specific version

Jenkinsfile
Want to set a specific kube-burner version to avoid issues getting latest version 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/regression-test/379/console
Similar functionality was added for kube-burner and [kube-burner-ocp](https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/511)
=> adding kube burner version to install

Jenkinsfile, scripts/nope.py
So this was a fun one I became aware of while uploading the 1.4 baselines - in #493 I update this piece of NOPE code to the following:
```python
for param in build_parameters:
del param['_class']
if param.get('name') == 'VARIABLE':
info['variable'] = int(param.get('value'))
if param.get('name') == 'WORKLOAD':
info['workload'] = str(param.get('value'))
else:
info['workload'] = JENKINS_JOB.split('/')[-1]
```
However, this led to all `kube-burner-ocp` jobs (`node-density-heavy` and `cluster-density-v2`) parsing out `kube-burner-ocp` for the workload rather than the actual workload from the `WORKLOAD` variable - but why?
```text
{'_class': 'hudson.model.StringParameterValue', 'name': 'WORKLOAD', 'value': 'node-density-heavy'
},
{'_class': 'hudson.model.BooleanParameterValue', 'name': …
```
=> Fix bug with NOPE tool incorrectly parsing workload

Jenkinsfile
Separating out moving components. 
This helps if the infra nodes were created but you know want to be able to move the ingress, monitoring or registry 
Infra pods had been created in previous step but wanted to be able to move the components but wasn't able to 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/cluster-post-config/1629/console
Passing job; https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cluster-post-config/118/
=> Cluster post config

scripts/loki/lokistack-1x-exsmall.yaml, scripts/loki/lokistack-1x-medium.yaml, scripts/loki/lokistack-1x-small.yaml
Hit `429` error again in `router-perf` - cluster still has a lot of resource capacity so going to increase this limit once more
=> Further increased Loki perStreamRateLimit

Jenkinsfile
E2e benchmarking no longer gets the latest kube-burner version, want to keep up to dat with what is in prow 
this would have to go before: https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/526
=> Removing kube burner version and read new index file

write_to_sheet/write_helper.py
Fixing duration issue in upgrade
```
10-17 13:49:41.902  Traceback (most recent call last):
10-17 13:49:41.902    File "<string>", line 1, in <module>
10-17 13:49:41.902    File "/home/jenkins/ws/workspace/_pipeline_write-scale-ci-results/write_to_sheet/write_loaded_results.py", line 22, in write_to_sheet
10-17 13:49:41.902      duration, versions = write_helper.get_upgrade_duration()
10-17 13:49:41.902    File "/home/jenkins/ws/workspace/_pipeline_write-scale-ci-results/write_to_sheet/write_helper.py", line 31, in get_upgrade_duration
10-17 13:49:41.902      earliesetStartingTime = datetime.max
10-17 13:49:41.902  AttributeError: module 'datetime' has no attribute 'max'
```
=> get upgrade duration

Jenkinsfile
The same as https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/541
=> [kube-burner-ocp] No longer rely on quay.io

Jenkinsfile
We've done the same changes in https://gitlab.cee.redhat.com/aosqe/jenkins-jcasc-n/-/merge_requests/1755 on Sep 27, 2023, and it improved the performance of Jenkins and OCP cluster.
Also with this change, we are not affected by quay.io outage.
=> [must-gather] No longer rely on quay.io

Jenkinsfile
The same as https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/541
=> [kube-burner] No longer rely on quay.io

upgrade_scripts/common.sh, upgrade_scripts/upgrade.sh
update code to extend the timeout of checking upgrade and ignore terminating pod
Jenkins Logs:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/liqcui-e2e-benchmarking-multibranch-pipeline/job/loaded-upgrade/110/console
Adding UPGRADE_WAIT_NUM to extend the timeout of checking check_upgrade.check_upgrade 
because ibmcloud will take more time to complete loaded upgrade, so we need to increase the timeout of check_upgrade.check_upgrade, the default value 300 isn't enough
=> update code to extend the timeout of checking upgrade

scripts/netobserv/flows_v1beta2_flowcollector.yaml
New `lokistack` mode does not require explicit namespace to be set - since we have always used the default (`netobserv`) namespace anyway, we can remove that from our flowcollector CRD.
Tested here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/460/
=> Remove explicit namespace from Loki config in flowcollector

Jenkinsfile
There is no need to find a baseline with the new scripts as it finds them for you
=> Benchmark comparison

Jenkinsfile
Since https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/570 NetObserv team is no longer using Mr. Sandman - if there is no need from the PerfScale team to keep this we can remove it from the `kube-burner-ocp` pipeline
=> Remove Mr. Sandman entirely

Jenkinsfile, scripts/README.md, scripts/netobserv.sh, scripts/queries/netobserv_dittybopper_upstream.json
- Using `python3.9` for all Touchstone runs (https://github.com/cloud-bulldozer/e2e-benchmarking/pull/671)
- Updated upstream Dittybopper to match downstream config
- Some updates to the `README`
=> Various NetObserv automation updates

Jenkinsfile, scripts/netobserv/flows_v1beta2_flowcollector.yaml
For additional flexibility, tested here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/538/
=> Add ability to change e2e-benchmarking repo and branch

scripts/queries/netobserv_touchstone_tolerancy_config.json, scripts/queries/netobserv_touchstone_tolerancy_rules.yaml
Part of [NETOBSERV-1543](https://issues.redhat.com/browse/NETOBSERV-1543)
Now that https://github.com/cloud-bulldozer/benchmark-comparison/pull/76 is in we can begin adding metrics where we typically see a value of '0' to our Touchstone Comparsion, which will allow us to track errored and dropped flows more explicitly  
Tested locally with Touchstone below:
```bash
[nathan@nathan-redhat netobserv-qe-scripts (crd-dir)]$ ./touchstone_compare.sh 0c6cdb12-ad06-4b4a-8fa2-fb2b92fdf7ff     c9a81e65-64e9-4cb1-84e9-8f0792913882
File ‘netobserv_touchstone_tolerancy_config.json’ already there; not retrieving.
File ‘netobserv_touchstone_tolerancy_rules.yaml’ already there; not retrieving.
egrep: warning: egrep is obsolescent; using grep -E
+-----------------------+-----------------------+------------+ …
```
=> Add in final comparison stats with 'zero' values

Jenkinsfile
Hitting some failures that seem related to csr's not returning within the timeout causing cerberus to fail
Had tried to hit this manually and not able to do so. Need to get this merged to see if it helps with spontaneous failures
Failure: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/cerberus/3878/console
Successful run after: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cerberus/340/console 
Bug: https://issues.redhat.com/browse/OCPQE-20561
=> Increasing timeout - cerberus

prow/generate_jobs_in_gsheet/get_periodic_jobs.py
Script would only print two days of the cron expression.
Now it can print more than two days of month fields in array format:
`At 0, on days ['1', '8', '15', '22'] of the month`
=> Handle more than two days in cron expression

prow/Dockerfile
For the bare metal new scenarios that are being introduced we need ssh in the image.
=> Add ssh to prow image

prow/generate_jobs_in_gsheet/get_periodic_jobs.py
Hypershift is no longer properly being called out in our gooogle sheet of the jobs since the name of the workflow changed from "hypershift" to hcp. This should help this issue
Ex: https://github.com/openshift/release/blob/a45d8237303d117149c08a5c4c56a558fd62dfbf/ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.14-nightly-x86.yaml#L97
=> Updating hcp option

scripts/queries/netobserv_prometheus_queries.yaml
Changing this promQL for 2 things:
- it was incorrectly looking at traffic going **from** the workloads, but the analog cAdvisor query looks at traffic going **to** the workloads (`container_network_receive_bytes_total{job="kubelet", metrics_path="/metrics/cadvisor", cluster="", namespace=~"node-density-heavy.*|ingress-perf|cluster-density.*"}`). So we need to change `SrcK8S_Namespace` to `DstK8S_Namespace`.
- changing `DstK8S_OwnerType="Deployment"` to `DstK8S_Type!="Service"`. The purpose is the same: eliminate duplicates resulting from the services layer. The new filters are more accurate.
=> Fix metric promql: Bps measured by netobserv

scripts/requirements.txt
numpy 2.0.0 was release on June 16 and breaking our tool with below error. Updating it to use older numpy for time being:
```
$ python nope.py --starttime 1718632785 --endtime 1718635754 --jenkins-job scale-ci/e2e-benchmarking-multibranch-pipeline/kube-burner-ocp --jenkins-build 1564 --uuid 3ac01e3b-6218-4458-9fc3-bb71580721a2 --jira NETOBSERV-1680-wo-loki-kafka-cd-50
Traceback (most recent call last):
File "/Users/memodi/workspaces/repos/ocp-qe-perfscale-ci/scripts/nope.py", line 18, in <module>
from elasticsearch import Elasticsearch
File "/Users/memodi/.local/share/virtualenvs/scripts-WBM3pJit/lib/python3.10/site-packages/elasticsearch/__init__.py", line 36, in <module>
from .client import Elasticsearch
File "/Users/memodi/.local/share/virtualenvs/scripts-WBM3pJit/lib/python3.10/site-pa …
```
=> use numpy < 2.0.0

scripts/netobserv/flows_v1beta2_flowcollector.yaml
this trickled in when I moved to use flowcollector template, having it in causing very high ebpf memory usage.
Sorry, this cause multiple bugs, hopefully it's the last one.
=> remove kafkaBatchSize

Jenkinsfile
temporary workaround to used forked repo, should be removed when https://github.com/cloud-bulldozer/benchmark-comparison/pull/77 is merged
=> workaround for numpy

Jenkinsfile, scripts/README.md, scripts/netobserv/flows_v1beta2_flowcollector.yaml, scripts/nope.py, scripts/queries/netobserv_touchstone_statistics_config.json
This has following changes and fixes:
- link Sheets to build description
- New ES fields for cross-referencing jenkins job and spreadsheets: buildUrl, uuid_replaced_info.
- use loki.batchWriteSize to 10 MB until [NETOBSERV-1766](https://issues.redhat.com//browse/NETOBSERV-1766) is fixed
- other minor fixes
[Success run](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/memodi-e2e-benchmarking-multibranch-pipeline/job/ss-links/11/) which links the spreadsheets as well in build info.
=> Spreadsheet links in build info and cross-reference in spreadsheets

prow/Dockerfile
Need kubectl cli since its not added with cli: latest we're now using
CC: @jtaleric 
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/55839/rehearse-55839-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.16-latest-x86-weekly-6nodes/1826308991307747328
=> Adding kubectl into base image 

Jenkinsfile
fix for error: `time=“2024-08-13T07:05:41Z” level=fatal msg=“invalid character ‘>’ in string escape code”`
tested this change here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/memodi-e2e-benchmarking-multibranch-pipeline/job/add-prom2/11/console
also fixing where nope.py failed with:
```
08-26 07:48:05.684  + python /home/jenkins/ws/workspace/ch-pipeline_netobserv-perf-tests/ocp-qe-perfscale-ci/scripts/nope.py --starttime 1724671933 --endtime 1724672631 --jenkins-job scale-ci/e2e-benchmarking-multibranch-pipeline/kube-burner-ocp --jenkins-build 1819 --uuid 1e8e691e-2da0-4067-8a00-c92408fa276b --noo-bundle-version
08-26 07:48:06.036  usage: nope.py [-h] [--debug] [--yaml-file YAML_FILE] [--starttime STARTTIME]
08-26 07:48:06.036 …
```
=> use 4.16 opm-rhel8 binary

scripts/loki/loki-released-subscription.yaml, scripts/loki/loki-unreleased-subscription.yaml
[NETOBSERV-1878](https://issues.redhat.com//browse/NETOBSERV-1878) use loki 6.0 channel for OCP >= 4.17
=> NETOBSERV-1878 use loki 6.0 channel for OCP >= 4.17

scripts/queries/netobserv_touchstone_tolerancy_config.json
[NETOBSERV-1715](https://issues.redhat.com//browse/NETOBSERV-1715) clean up tolerancy and fixes for NetObservCluster CPU/Mem PercentUtil metrics, ran a test with new config:
```
$ touchstone_compare.sh be417bf8-4366-4fef-9984-f0cbc27aa1c8 cbbead45-3e8b-48fd-a1fd-02ce82f83d80
File ‘netobserv_touchstone_tolerancy_config.json’ already there; not retrieving.
File ‘netobserv_touchstone_tolerancy_rules.yaml’ already there; not retrieving.
deviation is -28.92470763737363
+-----------------------+-----------------------+------------+--------+-----------+--------------------------------------+--------------------------------------+
|      metric_name      |      metric_name      |   metric   | result | deviation | be417bf8-4366-4fef-9984-f0cbc27aa1c8 | cbbead45-3e8b-48fd-a1fd-02ce82f83d80 | …
```
=> NETOBSERV-1715 clean up tolerancy and fixes for NetObservCluster CPU/Mem PercentUtil metrics

OWNERS
Looks like the owners in config and jobs come from this file, adding perfscale dev to align with the OWNERS in the step-registry
https://github.com/josecastillolema/release/blob/05ae225ad9869df0900201a76997d60172867fb8/ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/OWNERS#L1-L2
=> Adding more reviewers

Jenkinsfile, scripts/netobserv.sh
While loop to wait for loki-operator and bug fix in Jenkinsfile
this should prevent errors like:
```
10-14 07:31:12.867  + oc wait --timeout=180s --for=condition=ready pod -l app.kubernetes.io/name=loki-operator -n openshift-operators-redhat
10-14 07:31:12.867  error: no matching resources found
```
and 
```
10-14 11:46:42.726  /home/jenkins/ws/workspace/ch-pipeline_netobserv-perf-tests@tmp/durable-202ebc20/script.sh.copy: line 4: syntax error near unexpected token `)'
```
latter causes comparison to fail and marking whole run as Unstable.
=> While loop to wait for loki-operator and bug fix in Jenkinsfile

scripts/env.sh, scripts/netobserv.sh, scripts/netobserv/flows_v1beta2_flowcollector.yaml, scripts/queries/netobserv_dittybopper.json
[NETOBSERV-1874](https://issues.redhat.com//browse/NETOBSERV-1874) Netobserv reliability tests
the code changes here are improvements in general, should help reliability tests and also other performance tests.
- source env.sh should have all necessary env. vars for full stack installation. 
- defaults for some of variables.
- [NETOBSERV-1961](https://issues.redhat.com//browse/NETOBSERV-1961) have ebpf privileged mode by default.
- adds dashboards for file descriptor and goroutine thread to check for leaks.
=> NETOBSERV-1874 Netobserv reliability tests

Jenkinsfile
sync default instance type with prow ci
=> sync with prow ci

scripts/queries/netobserv_touchstone_tolerancy_config.json, scripts/queries/netobserv_touchstone_tolerancy_rules.yaml
Adding two metrics to KPIs:
- `nWorkloadBytesProcessedPerMinuteNetobserv`, which tells bandwidth captured by netobserv
- `nWorkloadBytesProcessedPerMinuteCadvisor`, which tells bandwidth captured via container metrics / cAdvisor
Both of them are interesting, as they can tell:
- That netobserv captured the expected amount of traffic, ie. not dropping too much, and checking correctness at the same time, ie. we haven't introduced a regression that miscounts bytes
- That the workload traffic isn't affected by netobserv (ie. a drop in cAdvisor metrics is an indication of performance regression with latency induced by netobserv)
Those metrics are more reliable than the number of flows for these goals because the workload bandwidth is supposed to be somewhat consistant across runs, whereas …
=> Add bandwidth metrics to KPIs

scripts/queries/netobserv_prometheus_queries.yaml
- Traffic returned from service is duplicated with returned traffic from pods
- Filter on eth0 to avoid counting duplicates, cf comments in https://issues.redhat.com//browse/NETOBSERV-1954
=> Do not count traffic returned from services in metrics + filter eth0

scripts/netobserv.sh
update AMQStreams operator memory limit to 1G as current limits of 384Mi is not enough for 250 nodes scenario
https://redhat-internal.slack.com/archives/C067V3MQP2S/p1733326466727439 
tested:
```
CSV_NAME=$(oc get csv -n openshift-operators -l operators.coreos.com/amq-streams.openshift-operators= -o jsonpath='{.items[].metadata.name}')
$ oc -n openshift-operators patch csv $CSV_NAME --type=json -p "[{"op": "replace", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/0/resources/limits/memory", "value": "1Gi"}]"
clusterserviceversion.operators.coreos.com/amqstreams.v2.8.0-0 patched
$ oc get csv -n openshift-operators -l operators.coreos.com/amq-streams.openshift-operators= -o jsonpath='{.items[].spec.install.spec.deployments[0].spec.template.spec.containers[0].resource …
```
=> increase AMQStreams Operator limit to 1Gi

upgrade_scripts/upgrade.sh
The pod check continuously fails but when it gets the pod logs the pods do not exist (go running/proper status) 
I don't think this step has been useful in finding any bugs and we can remove 
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/59872/rehearse-59872-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-loaded-upgrade-from-4.16-loaded-upgrade-416to417-24nodes/1867598081550192640
=> Taking out pod check

scripts/nope.py
error in perf job: https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/1477/consoleFull should be fixed 
```
01-23 17:40:47.138    File "/home/jenkins/ws/workspace/ch-pipeline_netobserv-perf-tests/ocp-qe-perfscale-ci/scripts/nope.py", line 895, in <module>
01-23 17:40:47.138      main()
01-23 17:40:47.138    File "/home/jenkins/ws/workspace/ch-pipeline_netobserv-perf-tests/ocp-qe-perfscale-ci/scripts/nope.py", line 586, in main
01-23 17:40:47.138      noo_start_time_epoch = get_epoch_from_iso(
01-23 17:40:47.138    File "/home/jenkins/ws/workspace/ch-pipeline_netobserv-perf-tests/ocp-qe-perfscale-ci/scripts/nope.py", line 86, in get_epoch_from_iso
01-23 17:40:47.138      utc_dt = …
```
=> use NOO container to get release info

scripts/build_info.sh
minor sed bug fix missed bundle created date: https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/1491/
=> minor sed bug fix

az_outbound_ports.sh
Adding back up way to find resource group if load balancer was not found 
Error here seen because didn't properly apply port forwarding 
https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/cluster-workers-scaling/5799/console
passing job seen here: https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cluster-workers-scaling/155/console
=> adding script to update outboudn ports on azure

upgrade_scripts/upgrade.sh
Adding arch type to avoid running into this error, when running multi-arch loaded upgrades 
```Could not find target version in 'https://amd64.ocp.releases.ci.openshift.org/graph' ```
more details here: https://github.com/openshift/release/pull/59743#issuecomment-2702905838
=> Adding arch_type

requirements.txt
For some time all [jobs](https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/post-results-to-es/) were failing because numpy version jumped over ES requirements.
We can try to using newer version of ES - but this should work.
=> Not using the highest version on numpy

Jenkinsfile, scripts/nope.py, scripts/queries/netobserv_touchstone_statistics_config.json, scripts/queries/netobserv_touchstone_tolerancy_config.json
=> Replace prod-netobserv-jenkins-metadata index with perf_scale_ci* index

Dockerfile.prow, scripts/nope.py
[NETOBSERV-2128](https://issues.redhat.com//browse/NETOBSERV-2128) This would help avoiding image building during the run and would be readily available. Also, don't bring token as it is likely the cause of logs being removed entirely in CI run, for [example](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/62759/rehearse-62759-periodic-ci-openshift-eng-ocp-qe-perfscale-ci-netobserv-perf-tests-netobserv-aws-4.19-nightly-x86-cluster-density-v2-250nodes/1910713106590339072/artifacts/cluster-density-v2-250nodes/netobserv-perf-test-metrics-upload/build-log.txt)
=> NETOBSERV-2128 Dockerfile for Prow CI and don't print token at info level

scripts/sheets/noo_perfsheets_update.py, scripts/sheets/sheets.py
With this change, we'd able to create and name spreadsheets as we like and no longer required to parse the e2e-benchmarking logs to update the sheets.
Generate comparison sheet:
```
$ ./noo_perfsheets_update.py --service-account memodi-perf-tests-tool-083ab166a2cc.json --csv-file /Users/memodi/Downloads/d2617789-d9bf-4a3d-a2f5-74972ac393fc_comparison.csv --name memodi-ndh-test2 --comparison
2025-05-01 16:48:09,185 __init__:49 INFO file_cache is only supported with oauth2client<4.0.0
2025-05-01 16:48:10,423 sheets:40 INFO Spreadsheet ID: 175DG6Pe-hbFMcXg5yQNAwhRhbOAob5eKIDu0d-JkL40
2025-05-01 16:48:10,593 base:270 INFO POST https://search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com:443/prod-netobserv-operator-metadata/_search [status:200 request:0.168s] …
```
=> NETOBSERV-2226 Create and share spreadsheets

scripts/netobserv/flows_v1beta2_flowcollector.yaml
Post bug fix [NETOBSERV-2254](https://issues.redhat.com/browse/NETOBSERV-2254) we dont require secondary-network config to see CUDN/UDN name
=> Remove secondaryNetworksConfig for UDN

scripts/sheets/noo_perfsheets_update.py
fix for below error found during [CD-v2 run](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-eng-ocp-qe-perfscale-ci-netobserv-perf-tests-netobserv-aws-4.19-nightly-x86-cluster-density-v2-250nodes/1935073451370876928): 
```
Exception: An error occurred: https://sheets.googleapis.com/v4/spreadsheets/1o3X8owRMG2IMsSMWYJGSN28QDUKlTuBGCJ8w_9pB4Sg/values/A1%3AG1000?valueInputOption=USER_ENTERED&alt=json returned "Requested writing within range [Sheet1!A1:G1000], but tried writing to row [1001]". Details: "Requested writing within range [Sheet1!A1:G1000], but tried writing to row [1001]">
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:84","func":"sigs.k8s.io/prow/pkg/entrypoint.Option …
```
=> increase the cell range

Jenkinsfile
OCP 4.13 reach end of life. I'm going to stop building new images for oc413 in Jenkins CI.
=> Bump default value of JENKINS_AGENT_LABEL from oc413 to oc419

Jenkinsfile
OCP 4.10 reach end of life. We've stopped building image for oc410 in Jenkins CI.
=> Bump default value of JENKINS_AGENT_LABEL from oc410 to oc419

scripts/README.md, scripts/queries/netobserv-orion-cluster-density-v2-ospst.yaml, scripts/queries/netobserv-orion-cluster-density-v2.yaml, scripts/queries/netobserv-orion-node-density-heavy-ospst.yaml, scripts/queries/netobserv-orion-node-density-heavy.yaml
[NETOBSERV-2034](https://issues.redhat.com//browse/NETOBSERV-2034)  Netobserv orion configs
Using `threshold` same as currently defined in touchstone. The `direction` config is defined as:
```
direction: 1 specifies to show positive changes
direction: 0 specifies to show both positive and negative changes
direction: -1 shows negative changes
```
Read more about `orion` [here](https://github.com/cloud-bulldozer/orion/?tab=readme-ov-file#direction)
=> NETOBSERV-2034  Netobserv orion configs

scripts/queries/netobserv-orion-cluster-density-v2-ospst.yaml, scripts/queries/netobserv-orion-cluster-density-v2.yaml, scripts/queries/netobserv-orion-node-density-heavy-ospst.yaml, scripts/queries/netobserv-orion-node-density-heavy.yaml, scripts/queries/netobserv_prometheus_queries.yaml, scripts/queries/netobserv_touchstone_statistics_config.json, scripts/queries/netobserv_touchstone_tolerancy_config.json, scripts/queries/netobserv_touchstone_tolerancy_rules.yaml
This reverts commit 802349789c639347816da2ce47c07fc7c4cbe4cc.
@memodi , I'd like to revisit adding metrics cardinality as this is something important to know when tracking down potential regressions. I will bring some changes that I hope will fix the issue that you saw - and if it doesn't, we should try to investigate/refine on live cluster, if possible, rather than reverting?
=> Reapply "Netobserv: track metrics cardinality (#760)" (#765)

prow/Dockerfile
By default ping is shipped with cap_net_raw=ep capability which prevents ping from running in unprivileged pods which results in CI errors such as:
```
+ ping -c 5 XXXXXXXXXX
/bin/bash: line 11: /bin/ping: Operation not permitted
```
This change removes the ping binary capability which should allow running the ping checks in the CI steps.
=> Remove ping capability
