openshift-eng/ocp-qe-perfscale-ci

Jenkinsfile
This branch will be used for writing the results of loaded-upgrade, upgrade and all scale-ci jobs (ex. cluster-density) to a google sheet
=> Adding jenkins file for write to sheet

Jenkinsfile, README.md
Need python 3.8 for ripsaw-cli
=> New cluster density with python 3.8 virtualenv

Jenkinsfile, README.md
Loaded upgrade test will
1. Create flexy job or use existing flexy cluster
2. run scale-ci job
3. Upgrade cluster by 1 or more steps
4. write out results
5. Destroy cluster if destroy parameters set to true
=> Adding loaded upgrade testing workload jenkinsfile

Jenkinsfile
Taking out the upgrade version parameter because it is no longer needed in my write to sheet script
Please review when you have time @kedark3
=> Taking out upgrade version parameter from write upgrade info

Jenkinsfile
This PR 
* adds in the proper vm type and region for Azure clusters
* Takes out unneeded upgrade variables
* Adds in the specific failure type to know what part of the loaded upgrade process failed
CC: @kedark3 @skordas
=> Adding azure region, taking out unneeded variables, adding failure type

Jenkinsfile, upgrade_scripts/check_upgrade.py, upgrade_scripts/upgrade.sh
This PR is no longer going to use the svt upgrade scripts; it will move them here to use
I also added in a way to artifact the must gather if the upgrade fails 
Please take a look when you can @kedark3
=> Adding in upgrade scripts and artifact must gather

Jenkinsfile, write_to_sheet/get_es_data.json, write_to_sheet/get_es_data.py, write_to_sheet/write_helper.py, write_to_sheet/write_loaded_results.py, write_to_sheet/write_scale_results_sheet.py, write_to_sheet/write_to_sheet.py
Putting write helper files into this repo. Needed to copy down the current repo and branch to be able to use the files. Please let me know if there's a better way to do this 
This incorporates https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/13, could close that one and just do this one
CC: @kedark3
=> Write helpers

write_to_sheet/write_helper.py, write_to_sheet/write_loaded_results.py, write_to_sheet/write_to_sheet.py
Missed taking out the strip from the tuple variable that now gets returned from the run function. 
And there's an extra space so the flexy informaiton was not getting properly
@kedark3 PTAL
=> Incorrect strip on tuple

Jenkinsfile, upgrade_scripts/check_upgrade.py
Updating upgrade with a couple of fixes 
* Timeout on waiting for nodes to update
* Issue with parameter not being set properly in Jenkinsfile
Fixes:
https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/18
CC: @skordas @kedark3
=> Upgrade test fixes

write_to_sheet/write_loaded_results.py, write_to_sheet/write_to_sheet.py
This fixes the version list that is printed out to the sheet for both loaded and normal upgrades
CC: @kedark3
=> Fixing version list

prow/Dockerfile
Update to quay.io Fedora 34 image and add the python3-pip package.
=> Update base image and packages to Fedora

Jenkinsfile
Adding fix for writing the pod-density results to the correct worksheet on the google sheet of results 
CC: @mffiedler @skordas PTAL when you can! Thanks
=> Pod density writing to wrong worksheet

prow/Dockerfile
Switch base image to python:3.9 on quay.io
=> Use quay.io/openshifttest/python:3.9

Jenkinsfile, README.md, write_to_sheet/get_es_data.py, write_to_sheet/write_helper.py, write_to_sheet/write_loaded_results.py, write_to_sheet/write_to_sheet.py
Fixing: 
* The versioning printed off was messed up and was printing the versions backwards 
* Also had an issue that the write to sheet with getting the pod latencies that I was able to fix 
```
12-15 14:31:36.763  v {'gte': '2021-12-15T19:29:02.000Z', 'lte': '2021-11-18T23:48:11.565Z', 'format': 'strict_date_optional_time'}
12-15 14:31:36.763  Status : FAIL 1 {
12-15 14:31:36.763    "error" : {
12-15 14:31:36.763      "root_cause" : [
12-15 14:31:36.764        {
12-15 14:31:36.764          "type" : "json_e_o_f_exception",
12-15 14:31:36.764          "reason" : "Unexpected end-of-input: expected close marker for Object (start marker at [Source: (org.elasticsearch.common.io.stream.InputStreamStreamInput); line: 1, column: 1])\n at [Source: …
```
=> Write to sheet updates for versioning

Jenkinsfile
Taking out extra spaces in jenkins file and adding correct job name to pass to write-to-sheets
=> Node density proper job name for writing to sheet

write_to_sheet/write_helper.py
Fixing the list of versions, with 4.10 the sorted function did not work properly to print of the list properly
=> Fixing correct ordering of versions

Jenkinsfile
This PR adds in the proper python 3.8 virtualenv and activates it as well as go back to the proper folder for the max namespaces to run
Also adds in the printing to a google sheet for this scale-ci job
=> Max namespaces python3.8 updates and write to file

Jenkinsfile
taking out job type param, goes along with https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/41
=> Pod density, write to file updates

Jenkinsfile
Taking out duplicate write to file parameter, goes with: https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/41
=> Taking out job type, node density

Jenkinsfile
Update to match changes in e2e-benchmarking
=> Remove pip3 install of requirements.txt - podnetwork

Jenkinsfile
=> Remove pip3 install of requirements.txt - serviceip

Jenkinsfile
Going back to Premium_LRS storage type, need storageaccounttype instead of storageclass type. Other PR for in cluster worker scale coming as well
=> Post config azure fix with storage

Jenkinsfile
hostnetwork test does not require cluster-post-config
=> Remove cluster-post-config for hostnetwork test

Jenkinsfile
hostnetwork test does not require cluster-post-config
=> Remove cluster-post-config for hostnetwork test, part 2

Jenkinsfile
Post-config job not needed for hostnetwork test
=> remove post-config job

Jenkinsfile
In most cases we want to save results to the file.
=> Write results to the file as default behavior.

Jenkinsfile
=> Adding alibaba and ibmcloud clouds

Jenkinsfile
Passing env variables to separate jobs being called from pod-density
=> adding env vars passing to jobs

Jenkinsfile
Adding env variables to pass to jenkins jobs for vsphere
=> adding env vars to build jobs and adding write to file

Jenkinsfile
Adding env variables to pass to jenkins jobs for vsphere
=> Adding env variables to pass to jobs

Jenkinsfile
Passing env variables to worker scaler and other jobs
=> Adding env vars to other jobs

Jenkinsfile
Adding env vars passing to other jobs for vsphere
=> Adding env vars and taking out job_type extra parameter

Jenkinsfile
Adding env variables to pass to jenkins jobs for vsphere
=> Passing env variables to jobs

OWNERS
Add @memodi as approver and @jechen0648 as reviewer.
=> Update OWNERS - memodi as approver and jechen0648 as reviewer

README.md
adding polarion test case and params
=> adding polarion test case and param

README.md
Adding polarion test case link and parameter sugguestions
=> Adding test case and parameter suggestions

README.md
Adding polarion test case link and results info
=> Adding polarion test case link

Jenkinsfile
Adding creation of vsphere cluster as well as getting the proxy varaibles and adding them to the current ENV_VARS to be passed to future jobs
=> Adding vsphere support

Jenkinsfile
Missed one place where the environment variables need to be passed to cluster scaling jenkins job
=> Max namespaces missing env_vars passing

Jenkinsfile
Adding in Ash flexy installation as well as some formatting to separate the parameters by type. See screenshot below of new look 
..../scale-ci/job/paige-e2e-multibranch/job/loaded-upgrade/285/console (failure was due to storage-perf being taken out, flexy installation and passing of env variables passed)
=> Loaded upgrades with Ash 

Jenkinsfile
Adding in describe of any not ready nodes and not running machines
....scale-ci/job/paige-e2e-multibranch/job/cluster-workers-scaling/90/console ( I lowered the attempts to be able to see the failure) 
Fixes: https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/89
=> Cluster workers scaling

Jenkinsfile, README.md
adding parameter help and polarion link for node-density
=> adding parameter help and polarion link for node-density

Jenkinsfile, README.md
Adding suggestion on number of parameters for test and polarion link
=> Adding help with parameters

Jenkinsfile, README.md
Adding in a link to the polarion TC and variable suggestions
=> Adding link to polarion TC and parameter help

Jenkinsfile, README.md
This will replace the pod-density, cluster-density, node-density, node-density-heavy, max-namespaces and max-services branches into one common location
This will allow us to more easily edit all these workloads in one common place. 
See passing job here: Jenkins/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner-2/5/
=> New Kube burner job with parameterized workload variable

Jenkinsfile
Based on Qiujie's comment [here](https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/103#issuecomment-1070509912), adding back the scaleup and down into this job to make running more flexible. 
Just won't pass the parameters from the loaded-upgrade so we don't run into double scaling isuses
=> Adding scale up and down back in

Jenkinsfile
https://issues.redhat.com/browse/OCPQE-9394
Add WRITE_TO_FILE check box to router-perf scale-ci job.
Tested with https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/qili-e2e-benchmark/job/router-perf-w2f/20
Edit some description and default value, refine the layout.
=> Router perf w2f

Jenkinsfile, OWNERS
Fixing incorrect variable if scale-ci job fails; found by Nathan so adding him to list of reviewers
@mffiedler do I need to also add him in the PROW owners list or is just here ok?
=> Adding correct result to not get null error

Jenkinsfile, write_to_sheet/get_es_data.py, write_to_sheet/write_helper.py, write_to_sheet/write_nightly_results.py, write_to_sheet/write_scale_results_sheet.py
This will output the nightly scale-ci to a new sheet and fixes a couple smaller issues in which there's an error and nothing is returned
https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/117
Running job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write_nightly_regression/19/console
=> Write nightly regression and fix of pod-density

Jenkinsfile, README.md
Adding in the concurrent builds workload that was just added to e2e-benchmark to the kube-burner job
=> Adding concurrent builds performance testing workload jenkinsfile

Jenkinsfile
Adding infra and workload nodes installation at top level 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/infra_loaded/2/console
=> Infra workload boolean into loaded-upgrade

Jenkinsfile
Adding in concurrent builds under kube-burner to loaded-upgrade with 2 new variables speicifc to that job type 
Also adding a little bit of spacing changes
=> Concurrent Builds in Loaded upgrade

Jenkinsfile
Adding in check to see if SCALE_UP is not set to the default value 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cluster-workers-scaling/115/console
=> Only scale if SCALE_UP is not default

Jenkinsfile
Adding different size options into profiles
Dependent on PR in ci-profiles: [253](https://gitlab.cee.redhat.com/aosqe/ci-profiles/-/merge_requests/253)
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/profiles_update/22/console
=> Sizing of profiles in profiles 

upgrade_scripts/check_upgrade.py
ex. https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/upgrade/167/console
Need more time for nodes to restart.
=> Increasing wait time.

Jenkinsfile, OWNERS, README.md, scripts/README.md, scripts/common.sh, scripts/console-plugin-patch.json, scripts/flows_v1alpha1_flowcollector.yaml, scripts/netobserv.sh, scripts/ripsaw-uperf-crd.yaml, scripts/run_netobserv_perf_comparison_tests.sh, scripts/run_uperf.sh, scripts/run_workloads.sh
Adding Jenkins CI for netobserv.
=> Netobserv perf tests

Jenkinsfile
fixing bugs results post merge. Verified jobs are able to run successfully:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/memodi-e2e-benchmarking-multibranch-pipeline/job/netobserv-bug-fixes/6/
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/memodi-e2e-benchmarking-multibranch-pipeline/job/netobserv-bug-fixes/5/
=> Netobserv bug fixes

.gitignore, scripts/README.md, scripts/nope.py
=> Added ability for NOPE to autoset cluster URL and token

Jenkinsfile
Taking out all the flexy installation logic from this job and moved to cluster-builder. Now need to just call the cluster-builder job and get id properly to continue with tests
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/call_install/18/console
=> Using flexy install helper in loaded-upgrade

Jenkinsfile, README.md
Want to be able to add in cluster health checks using cerberus at the end of test runs, this is the first step
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cerberus/109/
=> Adding jenkinsfile for cluster checks

scripts/README.md, scripts/nope.py
As the tool matures, so too must the README. This is the way.
=> Added additional guidance to README and console output

Jenkinsfile
Adding in check for ready status when adding infra and workload nodes
=> Ready test check for infra and workload nodes 

scripts/nope.py
Resolves [NETOBSERV-375](https://issues.redhat.com/browse/NETOBSERV-375)
=> Added netobserv operator data to JSON payload

Jenkinsfile, README.md
Adding more documentation around the scale options on this job. Also allowing the option to install infra and workload nodes if scale_up is 0
=> Adding infra and workload doc and option if not scaling

README.md, scripts/README.md, scripts/netobserv.sh
Added details on script usage as well as doing some general cleanup
=> Updated READMEs in repository

upgrade_scripts/upgrade.sh
Update script to support arm ocp environment
=> Update upgrade.sh to support arm ocp

.gitignore, scripts/README.md, scripts/nope.py, scripts/requirements.txt
Also did minor reformats/additons to general NOPE code and scripts README
Example of new benchmark env data using `--jenkins-job scale-ci/e2e-benchmarking-multibranch-pipeline/kube-burner` and `--jenkins-build 491`:
```json
"benchmarkEnv": {
"uuid": "09023530-a327-4c1c-bb23-ab877d6ee40b",
"jenkins_job_params": [
{
"_class": "hudson.model.StringParameterValue",
"name": "BUILD_NUMBER",
"value": "108879"
},
{
"_class": "hudson.model.StringParameterValue",
"name": "WORKLOAD",
"value": "node-density-heavy"
},
{
"_class": "hudson.model.BooleanParameterValue",
"name": "WRITE_TO_FILE",
"value": true
},
{
"_class": "hudson.model.StringParameterValue",
"name": "JENKINS_AGENT_LABEL",
"value": "oc411"
},
{
"_class": "hudson.model.StringParameterValue",
"name": "VARIABLE",
"value": "200"
},
{ …
```
=> Added benchmark env info to data JSON

Jenkinsfile, README.md
https://issues.redhat.com/browse/OCPQE-10499
=> Remove ENGINE, add BASELINE_UUID and COMPARISON_ALIASES

Jenkinsfile
Need to see the architecture type to properly add the infrastructure and workload nodes of the right types 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/scaling-arm/13/console
The infra and workload nodes got added correctly. The dittybopper pod just didn't go running in time. Will see if we should increase the wait time on that
=> Adding architecture type to cluster scaling 

Jenkinsfile
Adding cerberus check and cleanup options in kube-burner job
=> Adding cerberus and cleanup checks to kube-burner

Jenkinsfile, infra-node-machineset-aws-customervpc.yaml, workload-node-machineset-aws-customervpc.yaml
https://issues.redhat.com/browse/OCPQE-10988
=> Install infra and workload machinesets for aws customer vpc cluster

Jenkinsfile
Adding in when option for if you want to install dittybopper and install from a specific fork and branch
2 runs: 
[Installing infra and workload nodes](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cluster-post-config/83/console)
[Dittybopper install by itself from fork](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cluster-post-config/78/)
=> Adding optional dittybopper with params

Jenkinsfile
In [PR](https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/190) I changed the type of variables to boolean types, need to update those fields here and add dittybopper url/branch
=> Adding dittybopper varaibles 

write_to_sheet/write_helper.py, write_to_sheet/write_scale_results_sheet.py
Adding cloud information printed off to the google sheets with results. this will help with comparison when doing future runs  
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/writing_clouds/2/console
=> taking out ending stars and adding cloud type to sheets

Jenkinsfile
Need to be able to call the cluster-post-config in cluster-workers-scaling and properly pass the OSP parameters needed
Passing job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/osp_scale/2/console
=> Adding osp call to cluster-post-config

Jenkinsfile, write_to_sheet/write_helper.py, write_to_sheet/write_loaded_results.py, write_to_sheet/write_nightly_results.py, write_to_sheet/write_scale_results_sheet.py, write_to_sheet/write_to_sheet.py
With the addition of the env_vars to write out to the sheet it could contain multiple lines so need to pass it by a file 
Failed script: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/write-scale-ci-results/2035/
Passing now: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write-helper/9/console
=> Write helper

Jenkinsfile, infra-node-machineset-azure-customervpc.yaml, workload-node-machineset-azure-customervpc.yaml
infra and workload machinesets for vpn clusten in Azure.
Successful run with jenkins: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/skordas-e2e-bmp/job/cluster-post-config/7/console
=> CR for infra and workload nodes in vpn cluster.

infra-node-machineset-azure-customervpc.yaml, infra-node-machineset-azure.yaml, workload-node-machineset-azure-customervpc.yaml, workload-node-machineset-azure.yaml
Due issues with pulling images from quay.io ${TITLE}
=> Adding missing publicLoadBalancer to Azure machinesets

Jenkinsfile
Adding in a boolean cerberus check at the end of the router_perf test
Also adding gen_csv to generate the google sheet from benchmark-comparison
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/router-perf/14/
=> Adding router perf cerberus check and csv_gen

Jenkinsfile
Adding in cerberus check into network-perf
Also setting to be able to generate google sheet
=> Network perf cerberus check

scripts/NetObserv_Metrics.json, scripts/README.md, scripts/analyze_metrics.py, scripts/nope.py, scripts/requirements.txt
Non-NOPE changes made:
- Updated `NetObserv_Metrics.json` title fields
- Updated README with minor typo fixes, generalized Scale CI usage rather than just kube-burner
- Changed `requirements.txt` to soft dependency requirements rather than hard
NOPE changes made:
- Implemented ES uploads to QE server
- Made `starttime` and `endtime` required args
- Gave `step` arg a default value of `10`
- Added `--dump` arg to override ES upload and do local dump instead (previously default behavior)
- Changed how netobserv version is parsed for 0.1.3 changes
- Reformatted data schema as discussed with @memodi (additional work needed here, will be done in followup PR)
- Various improvements to logging/error handling
=> Implemented ES uploads in NOPE tool (and more!)

scripts/nope.py
Accidentally removed `query` from metadata for `datapoint` documents in #183 - reintroduced that as well as added some addition ES upload info such as time duration for upload
=> Added back in query as well as additional ES upload info

Jenkinsfile, OWNERS, README.md, scripts/README.md, scripts/common.sh, scripts/netobserv.sh, scripts/run_netobserv_perf_comparison_tests.sh, scripts/run_uperf.sh
Resolves [NETOBSERV-499](https://issues.redhat.com/browse/NETOBSERV-499)
=> Reconfigure Netobserv perf job to do install and config of NOO

Jenkinsfile
Using the python3.9 that is now on the jenkins nodes instead of installing it in the script
=> Taking out python3.9 installation

.gitignore, Jenkinsfile, scripts/README.md, scripts/netobserv.sh
Resolves [NETOBSERV-502](https://issues.redhat.com/browse/NETOBSERV-502)
=> Added stages for scaling and dittybopper installation

Jenkinsfile
Changes can be seen live here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/kube-burner/build?delay=0sec
=> Reformatted kube-burner template

Jenkinsfile
Alibaba cloud scaling consistently times out, increasing wait time to 140 minutes
=> Increasing wait time for alibaba scaling

Jenkinsfile
Adding in the new feature for ignoring pods with certain namespaces 
https://github.com/redhat-chaos/cerberus/pull/178
=> Adding redhat-chaos and ignore pods in namespaces

Jenkinsfile, scripts/README.md, scripts/netobserv.sh, scripts/netobserv_dittybopper_ebpf.json, scripts/netobserv_queries_ebpf.yaml, scripts/nope.py
Did some minor cleanup on a few things as well
=> Automation changes now that eBPF will be default collector agent

Jenkinsfile, scripts/README.md, scripts/netobserv.sh, scripts/nope.py
Resolves [NETOBSERV-528](https://issues.redhat.com/browse/NETOBSERV-528)
=> Removed ipfix references from automation

Jenkinsfile, README.md
Tested with job on my own branch https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/qili-e2e-benchmark/job/regression-test/107/
=> Regression test

Jenkinsfile
Want to get upstream user to properly give access to user in google sheets from loaded-upgrades
Add in new variable for cerberus to ignore pods with certain names
=> Get upstream user when possible and cerberus var

Jenkinsfile
Fixes
* Cerberus check with ignored pods
* write to file at high level
* formatted parameters
* get proper upstream user
run here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/etcd-perf/25/console
=> Add cerberus check and top level write to file

Jenkinsfile
adding upstream user when running from loaded-upgrade jobs and cerberus pod ignore pattern
=> adding upstream user if needed and cerberus pod ignore pattern

Jenkinsfile
Now has consistent styling and spacing
=> Cleaned up kube-burner formatting

Jenkinsfile
Also moved the agent definition as the previous definition made it unable to run the post step
=> Added kube-burner output to archived artifacts

Jenkinsfile, README.md
Now has consistent styling and spacing, similar to #234
=> Cleaned up router-perf formatting

Jenkinsfile
Adding support for ARM registry to be able to add new scale-ci profiles for ARM.
=> Adding support for ARM registry.

Jenkinsfile, scripts/netobserv.sh
Adding Kafka support in scripts and Jenkinsfile. [NETOBSERV-523](https://issues.redhat.com/browse/NETOBSERV-523) and [NETOBSERV-524](https://issues.redhat.com/browse/NETOBSERV-524)
[Success run](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/memodi-e2e-benchmarking-multibranch-pipeline/job/kafka-update/8/console)
=> kafka support

Jenkinsfile
Similar to https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/235
=> Added router-perf output to archived artifacts

scripts/netobserv.sh
service-monitor for FLP in Kafka mode, missed in PR # 240
=> Kafka service monitor

Jenkinsfile, README.md, scaling.sh
Moved the code that waited for nodes to be ready into a resuable function. 
Adding code for when we are scaling down and to only match machinesets based on if they are worker types
=> Adding scale down sizing

scaling.sh
During the scaling process, the count of leftover machine sets were being applied to all machinesets not just 1 of them. This was causing the scaling job to never get to the expected count becuase it was too high 
```
09-06 10:45:17.796  current worker count 3
09-06 10:45:17.796  worker scale count 75
09-06 10:45:17.796  ++ echo scaleci12-6821-dvbk9-worker-a scaleci12-6821-dvbk9-worker-b scaleci12-6821-dvbk9-worker-c scaleci12-6821-dvbk9-worker-f
09-06 10:45:17.796  + for machineset in $(echo $worker_machine_sets)
09-06 10:45:17.796  + oc scale machinesets -n openshift-machine-api scaleci12-6821-dvbk9-worker-a --replicas 18
09-06 10:45:18.362  machineset.machine.openshift.io/scaleci12-6821-dvbk9-worker-a scaled
09-06 10:45:18.362  + for machineset in $(echo $worker_machine_sets)
09-06 …
```
=> Get 1 machine to get left over machine count

.gitignore, Jenkinsfile, README.md, scripts/README.md, scripts/netobserv.sh, scripts/nope.py, scripts/requirements.txt, scripts/sandman.py
Resolves [NETOBSERV-503](https://issues.redhat.com/browse/NETOBSERV-503)
=> Implemented workload runs and NOPE tool support

Jenkinsfile
Need to set a default user so that when the cron jobs are kicked off the results are still sent to someone
=> Kube burner default user

Jenkinsfile
The default user wasn't working properly 
In job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/router-perf/19/console
Properly setting email still 09-08 10:29:58.644  EMAIL_ID_FOR_RESULTS_SHEET=prubenda@redhat.com
=> adding different defualt user method

Jenkinsfile, scripts/flows_v1alpha1_flowcollector_lokistack.yaml, scripts/netobserv-catalogsource.yaml
- reflects recent changes in the Operator.
- update catalog image location.
=> Update for new flowcollecto and other changes

Jenkinsfile, scripts/deploy-loki-aws-secret.sh
Also updated a couple of `when` conditions
=> Updated default Loki bucket name

README.md
Want to add more information about the variables that are present on this job
=> Post config readme

scripts/netobserv.sh
All times are now `1`, `30`, or `60`
=> Increased sleep times in netobserv.sh

Jenkinsfile, scripts/README.md, scripts/console-plugin-patch.json, scripts/flows_v1alpha1_flowcollector_lokistack.yaml, scripts/flows_v1alpha1_flowcollector_versioned_lokistack.yaml, scripts/loki-storage-1.yaml, scripts/loki-storage-2.yaml, scripts/netobserv-catalogsource.yaml, scripts/netobserv.sh, scripts/netobserv_dittybopper_ebpf.json, scripts/netobserv_dittybopper_ipfix.json, scripts/netobserv_queries_ebpf.yaml, scripts/netobserv_queries_ipfix.yaml, scripts/noo-main-subscription.yaml, scripts/noo-released-subscription.yaml, scripts/nope.py, scripts/operator_group.yaml, scripts/service-monitor-kafka.yaml, scripts/service-monitor.yaml
In response to changes made in [NETOBSERV-373](https://issues.redhat.com/browse/NETOBSERV-373) and [NETOBSERV-433](https://issues.redhat.com/browse/NETOBSERV-433)
=> Changing name endpoints for perf automation

Jenkinsfile
Tested here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-auto-changes/8/
=> Updated build description with more info

Jenkinsfile, scripts/netobserv_dittybopper_ebpf.json, scripts/sandman.py, scripts/touchstone_csv.sh
Furthering efforts to get key information from the Jenkins console log to the build description
=> Enhanced time parsing and logging

Jenkinsfile, write_to_sheet/write_nightly_results.py, write_to_sheet/write_scale_results_sheet.py
Adding profile and profile scale size to nightly sheet printing
Successful run: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write-to-sheets/3/
=> Write to sheets - adding profile into nightly 

Jenkinsfile, check_kube_burner_ns.py, set_namespace_list.py
Need to do all getting of repositories before setting the proxy settings 
Needs to be added in addition to https://github.com/redhat-chaos/cerberus/pull/184 for ticket: https://issues.redhat.com/browse/OCPQE-12251
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cerberus/300/console
=> Adding get before setting proxy settings

Jenkinsfile, scripts/flows_v1alpha1_flowcollector_lokistack.yaml, scripts/flows_v1alpha1_flowcollector_versioned_lokistack.yaml, scripts/netobserv.sh, scripts/nope.py
Resolves [OCPQE-12293](https://issues.redhat.com/browse/OCPQE-12293)
=> Added Cerberus check to job and update CRDs

Jenkinsfile
Adding check if workload was blank to not error out
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cerberus/304/console
=> Cerberus check if workload is blank

Jenkinsfile
Can be seen here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/build?delay=0sec
=> Added links to workload docs in template

Jenkinsfile
Similar issue addressed in kube-burner 
https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/285
=> Getting all types of output

Jenkinsfile
Adding in option to run cerberus and cleanup, when passing blank workload it'll clean up all namespaces that have the kube-burner-job label no matter the value
Needs to be added after PR: https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/274
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/regression-test/6/console
=> Adding cerberus and cleanup to regression-test

Jenkinsfile
Adding ability to pass multiple parameters to comparison config, so exposing that variable in jenkins
=> adding new comparison config file parameter

Jenkinsfile
Adding in uperf touchstone config files and can reset at the users use case
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/network-perf/49/console
=> Adding comparison config defaults

Jenkinsfile
Changes to support google sheet generation for:
https://issues.redhat.com/browse/OCPQE-11961 - OCP-40557 - Replace loaded worker nodes with larger instances
https://issues.redhat.com/browse/OCPQE-12152 - Extend automation for "OCP-40557 - Replace loaded worker nodes with larger instances" to other providers.
Jenkins Run:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/svetsa-e2e-benchmarking-multibranch-pipeline/job/regression-test/8/console
File generated: https://docs.google.com/spreadsheets/d/1jrnS05dd2p3WM63TIOXNYqW0KDWXoboSewYa3_hffXk/edit#gid=1321307691
=> Accomodate Google sheet creation.

install_infra_work.sh
See in the below job that at first it had 0 replicas and retried till there were 2 before moving on 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/prom_moving/11/console
=> Adding correct type of comparison

README.md
Clarifying the different steps the upgrade ci takes here
=> Upgrade readme clarifications

write_to_sheet/write_loaded_results.py
Write nightly loaded-upgrade results to new nightly sheet
=> Adding nightly laoded upgrade to new sheet

Jenkinsfile, scripts/README.md, scripts/netobserv_touchstone.json, scripts/nope.py
Resolves [NETOBSERV-620](https://issues.redhat.com/browse/NETOBSERV-620)
=> Altered index strategy in NOPE and Touchstone

Jenkinsfile
As discussed with @paigerube14
=> Added Jenkins override for EMAIL_ID_FOR_RESULTS_SHEET var

Jenkinsfile, write_to_sheet/write_loaded_results.py, write_to_sheet/write_nightly_results.py, write_to_sheet/write_scale_results_sheet.py, write_to_sheet/write_to_sheet.py
Printing user who ran the job to sheet 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write-scale-ci-results/152/console
=> Adding user data to sheet

Jenkinsfile, scripts/README.md, scripts/flows_v1alpha1_flowcollector_versioned_lokistack.yaml, scripts/netobserv.sh, scripts/noo-main-subscription.yaml, scripts/noo-released-subscription.yaml, scripts/nope.py
Resolves [NETOBSERV-615](https://issues.redhat.com/browse/NETOBSERV-615)
=> Added S3 bucket usage calculation

scripts/flows_v1alpha1_flowcollector_versioned_lokistack.yaml, scripts/netobserv_queries_ebpf.yaml
also, removing group_left queries since its not playing well over http api. I'll do  PR for e2e-benchmarking to update touchstone config.
=> image tag fix and more queries

scripts/netobserv.sh
minor change as stated in title
=> append preserve to s3 bucketname if cluster name has preserve

Jenkinsfile, scripts/netobserv.sh, scripts/nope.py, scripts/requirements.txt, scripts/sandman.py
Also added an additional `sleep` to Kafka install script
=> Added colors to Python logging output

Jenkinsfile
Adding in regression test to run from loaded-upgrade
=> Adding regression test to option in loaded-upgrade

Jenkinsfile, README.md, kraken.sh, kraken_pod.sh, set_kraken_files.sh
Couple of successful runs: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kraken/
=> Start of kraken in jenkins

Jenkinsfile
Adding rhel8 to the cucushift label
=> Rhel8 cucushift label

Jenkinsfile
https://issues.redhat.com/browse/OCPQE-12517
=> add quay as registry for z-stream and ec builds

scripts/lokistack-1x-exsmall.yaml, scripts/lokistack-1x-medium.yaml, scripts/lokistack-1x-small.yaml, scripts/netobserv_dittybopper_ebpf.json, scripts/netobserv_queries_ebpf.yaml, scripts/nope.py
Also, increasing the default size in nope.py since I don't think we need 10s granular data.
=> updates to dashboard, queries, loki CRD

Jenkinsfile
Adding scale up and down to regression 
Updating description
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/regression-test/41/
=> Adding scaleup and down to regression-test

scripts/loki-ratelimit-alert.yaml, scripts/netobserv.sh
Adding loki alert for rate limits.
=> loki alert

Jenkinsfile
Adding in arch type for quay image url's 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cluster-builder/8/console: see sub flexy job that has proper url
=> Cluster builder arch type 

Jenkinsfile
Change according to discussion here https://github.com/cloud-bulldozer/e2e-benchmarking/issues/519#issuecomment-1331964622
=> Update default clients to adapt to maxconn change in 4.12

Jenkinsfile
See proper passing of variable to cluster-builder based on parameters passed: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/loaded-upgrade/354/console
For jira ticket: https://issues.redhat.com/browse/OCPQE-13061
=> adding arch type option to pass to cluster-builder

Jenkinsfile
Adding slack integration into job itself as the old way continues to get outdated
Also with Nathans help I added the workload name to the displayed name of the job
=> Adding workload type to name and slack integration

Jenkinsfile, scripts/lokistack-1x-medium.yaml, scripts/netobserv.sh, scripts/noo-main-subscription.yaml, scripts/nope.py
Changes made:
- Additions to Jenkins logging
- Fixed bug in `deploy_lokistack` where if `$WORKLOAD` wasn't set it would generate an invalid S3 bucket name
- Fixed bug where multiple artifacts caused Mr. Sandman to fail
- NOPE tool now collects Kafka broker data (I've updated ES/Kibana for this as well)
- Added `limits` block to `lokistack-1x-medium` CRD
- Added ability to configure NOO Controller Manger Pod Memory Limit
- Reorganized and enhanced deletion functions
- Updated noo main subscription channel 
- Renamed "release" CRDs to "upstream"
=> Updates based on recent testing

install_infra_work.sh
Adding wait for prometheus route to be up and give success. 
```
14:39:52 prom status 
parse error: Invalid numeric literal at line 1, column 7
14:39:57 prom status 
parse error: Invalid numeric literal at line 1, column 7
14:40:03 prom status 
parse error: Invalid numeric literal at line 1, column 7
14:40:08 prom status 
parse error: Invalid numeric literal at line 1, column 7
14:40:13 prom status 
parse error: Invalid numeric literal at line 1, column 7
14:40:19 prom status 
parse error: Invalid numeric literal at line 1, column 7
14:40:24 prom status 
parse error: Invalid numeric literal at line 1, column 7
14:40:30 prom status 
parse error: Invalid numeric literal at line 1, column 7
14:40:35 prom status 
parse error: Invalid numeric literal at line 1, column 7
14:40:40 prom status …
```
=> Wait for prometheus to be up 

Jenkinsfile
Adding couple of new test cases for [OCPQE-13453](https://issues.redhat.com/browse/OCPQE-13453)
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner/163/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner/164/console
Will need to experiment with numbers of iterations to pass to each of these new tests which will be covered in another sub ticket
=> Adding couple new case types

scripts/deploy-loki-aws-secret.sh, scripts/netobserv.sh, scripts/nope.py
Also made a small change to `delete_kafka` so the Strimzi operator itself would be removed
Resolves [OCPQE-13591](https://issues.redhat.com/browse/OCPQE-13591)
=> Added Loki Operator version to NOPE data collection

install_infra_work.sh, workload-node-machineset-azure.yaml
Workload node was trying to set/create public ip and causing an error. 
Need to increase the amount of retries while monitoring statefulsets get created
Passing job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cluster-post-config/109/console
=> Public ip false and increasing retries 

Jenkinsfile
Adding other jobs to run in parallel with kraken/cerberus
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/chaos-parallel/26/
=> Chaos parallel with more job types

write_to_sheet/write_scale_results_sheet.py
Trying to add in the new updated url's for kube-burner tests with grafana
=> Adding new grafana data source

scripts/subscriptions/netobserv-source-subscription.yaml
=> Updated source subscription channel

Jenkinsfile
Adding in call to post-to-slack job instead of re-writing same code in all jobs that we want to post to slack 
dependent on https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/350 going in first 
Passing job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner/180/
=> Adding post to slack job

Jenkinsfile, OWNERS
Adding a post to slack job to be called at the end of other jobs. Made this usable for any slack channel in Internal Red Hat
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner/180/
=> Post to slack

Jenkinsfile
=> Adding post to slack

Jenkinsfile
=> adding slack send

Jenkinsfile, OWNERS, README.md
Successfully got must-gather to run with increased pod memory and cpu sizing. Will want to add to sub jobs to gather data on failures 
@qiliRedHat @svetsa-rh @skordas PTAL and let me know which jobs we feel this would be the most beneficial 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/must-gather/21/console
=> Adding must gather jenkins job

Jenkinsfile
https://issues.redhat.com/browse/OCPQE-13633
Tested with https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/qili-e2e-benchmark/job/router-perf/19 -Passed
=> router perf Kube with QE es server

Jenkinsfile
Take out user display data as it is not used anywhere else
=> Must gather take out user 

Jenkinsfile
Adding post result when job is finished
=> Adding post result to slack

Jenkinsfile
Add in call to must gather under cerberus if failure
PR https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/360/ must go in first
=> Must gather option in kube-burner

Jenkinsfile
Add in call to must gather under cerberus if failure
PR https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/360 must go in first
=> Adding must gather option

Jenkinsfile
Adding in must gather parameter passing to all sub jobs: 
dependent on https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/366, https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/365, https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/360, https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/354
=> Adding must gather option to all sub jobs

Jenkinsfile
Adding in slack call and must gather check 
PR https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/360 must go in first
=> Adding send slack and must gather to cerbeerus

Jenkinsfile
Adding in. must gather option into etcd 
PR https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/360 must go in first
=> Adding must gather option etcd perf

Jenkinsfile
Adding in must gather boolean parameter to only collect must gather when parameter is set and cerberus job fails 
Dependent on https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/353/ getting merged first
=> Cerberus with must gather 

Jenkinsfile
Missing script option in router perf
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/router-perf/908/console
=> missing script tag

Jenkinsfile, README.md
Ticket: https://issues.redhat.com/browse/OCPQE-13658
=> Adding NetworkPolicy test case

Jenkinsfile
To be consistent with https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/376
=> Adding Networkpolicy TC description.

scripts/README.md, scripts/env.sh, scripts/netobserv-operatorgroup.yaml, scripts/netobserv.sh, scripts/subscriptions/netobserv-operatorhub-subscription.yaml, scripts/subscriptions/netobserv-source-subscription.yaml
addressing broken Source installation and enhancement to deploy kafka using script
/cc @Amoghrd @nathan-weinberg
=> addressing broken Source installation and enhancement to deploy kafka

Jenkinsfile
Want to add churn on by default to be able to better align with the perfscale dev team
=> Adding churn by default

Jenkinsfile
Going along with pr https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/381 want to add churn on by default
=> adding churn and cluster density numbers increase

Jenkinsfile
Adding script tag to regression test
=> adding script

Jenkinsfile, write_to_sheet/write_loaded_results.py, write_to_sheet/write_scale_results_sheet.py
Fixing issue with not printing out google sheet as well as error in router perf printing off
Adding profiles to nightly loaded-upgrade job
Successful job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write-to_sheet/77/console
=> Addding proifle info to nighlty loaded-upgrade and router perf fix

Jenkinsfile, scripts/README.md, scripts/catalogsources/qe-unreleased-catalogsource.yaml, scripts/netobserv.sh
=> Added IIB override option to Internal installation

Jenkinsfile, write_to_sheet/write_scale_results_sheet.py
Updates for both loaded-upgrade and kube-burner jobs needed
passing jobs of each type: 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write-to_sheet/79/parameters/
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write-to_sheet/85/console
=> Taking out force parameter

Jenkinsfile
Tested here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/78/
=> Made configuration of NOO and FLP resources optional

Jenkinsfile
Wrong parameter type when printing profile information to google sheet
=> Adding string of profile parameters

Jenkinsfile, scripts/queries/netobserv_touchstone_config.json
Related to https://github.com/cloud-bulldozer/e2e-benchmarking/pull/550
=> Updated NetObserv Touchstone config files and relevant automation

Jenkinsfile, help_find_flexy_uuid.py, helper_uuid.py, post_uuid_to_es.py, requirements.txt, update_es_uuid.py
Was able to test using the long run with the cluster still running. Will need to add this to steps similar to write-to-sheet to be able to do calls on the cluster
https://search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com/_plugin/kibana/app/discover#/doc/5322f3a0-b899-11ed-b8a6-43da4fbe743a/perfscale-jenkins-metadata?id=OcS9LYcBQj4tyFF-qMTt
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/perfscale-es/34/console
Lots of subsequent PR's will be needed in gitlab to include this job
=> Adding post to es of jenkins data

Jenkinsfile, scripts/netobserv.sh, scripts/netobserv/flows_v1beta1_flowcollector.yaml, scripts/queries/netobserv_dittybopper_upstream.json
- Exposed `eBPF` memory limit and `router-perf` workload options for configuration
- Added `DESTROY_CLUSTER` option to cleanup stage
- Added `PROFILE_PORT` to flowcollector CRD
- Minor updates to upstream Dittybopper config
=> Added additional features to pipeline, updated CRD

install_infra_work.sh
@paigerube14 @qiliRedHat Can you ptal?
Passing run:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/svetsa-e2e-benchmarking-multibranch-pipeline/job/cluster-post-config/7/console
=> Update token creation to be compatible with older versions. Exit otherwise.

Jenkinsfile
Need to add blank option to only run upgrade with chaos and cerberus
=> Adding blank option

Jenkinsfile, scripts/netobserv.sh, scripts/netobserv/flows_v1beta1_flowcollector.yaml, scripts/nope.py, scripts/queries/netobserv_dittybopper_upstream.json
- Exposed `eBPF` memory limit and `router-perf` workload options for configuration
- Added `DESTROY_CLUSTER` option to cleanup stage
- Added `PROFILE_PORT` to flowcollector CRD
- Minor updates to upstream Dittybopper config
- Reduced number of logs generated by FLP
- Extended NOPE tool to attempt multiple token capture methods
- Altered AWS deletion func to try and make it more reliable
=> Added additional features to pipeline, updated CRDs (round 2)

Jenkinsfile, scripts/README.md
=> Renamed FLP sampling rate to eBPF sampling rate

scripts/netobserv.sh
Per request by @Amoghrd :smile:
=> Increased timeout for LokiStack pods

Jenkinsfile
Adding in more files that we can gather data in our google sheets with: 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner-touchstone/7/console
=> Adding more comparison configs

Jenkinsfile, OWNERS, README.md, scripts/README.md, scripts/netobserv/netobserv-official-subscription.yaml, scripts/netobserv/netobserv-operatorhub-subscription.yaml, scripts/netobserv/netobserv-source-subscription.yaml
Resolves [NETOBSERV-854](https://issues.redhat.com/browse/NETOBSERV-854)
Also did some other minor stuff
=> Changed release channels for NetObserv subs

Jenkinsfile
After [Pr](https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/408), need to update calls with new variables
=> Adding write with new variables

Jenkinsfile
After [Pr](https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/408), need to update calls with new variables
=> new variables for write - loaded upgrade

scripts/queries/netobserv_prometheus_queries.yaml
Cleaned up and rearranged the file to make it more readable and easier to identify gaps we might want to address as part of [NETOBSERV-1001](https://issues.redhat.com/browse/NETOBSERV-1001)
=> Cleaning up the Prometheus query file

Jenkinsfile
Allthe regression results have not been printing to the google sheet becuase of a bug with this code needs to go in ASAP 
Successful job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write-to_sheet/126/console
Failure I'm fixing: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/write-scale-ci-results/5157/parameters/
=> Write to sheet nightly regression tests

Jenkinsfile
Adding downstream change in must gather to upper job 
https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/423
https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/422
=> Kube burner cerberus must gather options

Jenkinsfile
After pr: https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/422 gets merged need to add image/image-stream options upstream as well
=> Adding image/image-stream option for must gather

Jenkinsfile
Adding downstream change in must gather to upper job 
https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/423
https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/422
=> Adding cerberus check image options to router-perf

Jenkinsfile
Adding image/image-stream options for must gather at highest level. Also etcd-perf is no longer used/supported so removing workload type
=> adding image stream for cerberus and no etcd-perf

scripts/nope.py, scripts/queries/netobserv_prometheus_queries.yaml, scripts/queries/netobserv_touchstone_config.json
Resolves [NETOBSERV-1006](https://issues.redhat.com/browse/NETOBSERV-1006)
=> Adding processor arch tracking to Perf automation

Jenkinsfile, scripts/README.md, scripts/nope.py, scripts/queries/netobserv_touchstone_config.json
Resolves [NETOBSERV-1007](https://issues.redhat.com/browse/NETOBSERV-1007)
=> Adding ability to tie Jiras to NOPE runs

Jenkinsfile
Adding some missing description.
Increasing readability of workload description.
Cosmetic change only.
=> Adding some missing description.

OWNERS
Adding users to be more in line with owners in step-registry in prow
=> Adding users to be equal with other owners

Jenkinsfile
Depends on PR https://github.com/cloud-bulldozer/e2e-benchmarking/pull/535 to merge
Add COMPARISON_RC (default=1) to let Benchmark-comparison return 1 if tolerancy check fails.
Add Tolerancy to replace tolerancy in [mb-tolerancy-rules.yaml](https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/router-perf-v2/mb-tolerancy-rules.yaml)
=> router-perf job fails when benchmark comparison fails

scripts/sandman.py
Need to add support for network-perf-v2 to properly print results from test type to our google sheet using the sandman script. This test type does not have a UUID. Let me know your thoughts
Used output file here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/network-perf-v2/2/
=> Adding network perf option

Jenkinsfile
Updating kube burner ocp to use the e2e-benchmarking version and stay consistent with our setup
=> Kube burner ocp

Jenkinsfile
https://issues.redhat.com/browse/OCPQE-14446
PR https://gitlab.cee.redhat.com/aosqe/jenkins-jcasc-n/-/merge_requests/1589 depends on this pr's merge
=> add large to PROFILE_SCALE_SIZE choices

Jenkinsfile
Make write to elastic search its own boolean parameter
Fixes: https://issues.redhat.com/browse/OCPQE-15493
Passing job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner/219/console
=> make write to es a separate boolean

scripts/nope.py, scripts/queries/netobserv_touchstone_config.json
Resolves [NETOBSERV-1086](https://issues.redhat.com/browse/NETOBSERV-1086)
=> Track OCP version with NOPE/Touchstone

scripts/nope.py, scripts/queries/netobserv_touchstone_config.json
Reverts openshift-qe/ocp-qe-perfscale-ci#443
=> Revert "Track OCP version with NOPE/Touchstone"

scripts/nope.py, scripts/queries/netobserv_touchstone_config.json
Resolves [NETOBSERV-1086](https://issues.redhat.com/browse/NETOBSERV-1086)
=> Track OCP version with NOPE/Touchstone (round 2)

Jenkinsfile
Missing network-perf-v2 in es results data
=> adding network-perf-v2 to es resutls

Jenkinsfile
Want to only add baseline data if passing. Also want to always add baseline to gather more data
=> Adding only upload baseline if pass

scripts/README.md, scripts/queries/netobserv_touchstone_rules.yaml
Partially resolves: NETOBSERV-936 
Adding touchstone comparison rules, tolerances and Readme.
```
$ touchstone_compare -url $ES_URL -u d9be1710-abdb-420d-86da-883da583aa03 363eb0de-9213-4d9c-a347-849007003742  --config ~/touchstone_configs/netobserv_touchstone_config.json --tolerancy-rules ~/touchstone_configs/netobserv_touchstone_rules.yaml 2> /dev/null | egrep -iB 3 -A 1 "Pass|fail"
+--------------------------------+--------------------------------+------------+--------+-----------+--------------------------------------+--------------------------------------+
|          metric_name           |          metric_name           |   metric   | result | deviation | d9be1710-abdb-420d-86da-883da583aa03 | 363eb0de-9213-4d9c-a347-849007003742 | …
```
=> adding touchstone comparison rules

Jenkinsfile
Add write data to elastic search
=> adding write to es

Jenkinsfile
Missing comma giving error 
error: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/post-results-to-es/469/console
=> missing comma

Jenkinsfile
Want to add posting results to elastic search
=> Adding es results

upgrade_scripts/upgrade.sh
Add new function to check failed pods after loaded upgrade.
=> adding check failed pods functions for loaded upgrade

upgrade_scripts/upgrade.sh
Ignore installer pod error and adding retry step to avoid temp failed pod issue
The new Jenkins test job is:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/liqcui-e2e-benchmarking-multibranch-pipeline/job/loaded-upgrade/80/
=> update code to fix temp failed pod issue

Jenkinsfile
Removing max-namespace and max-services
=> Kube burner remove workloads

Jenkinsfile
Adding qe email alias for nightly results
=> Kube burner email alias

Jenkinsfile
Resolves [NETOBSERV-1105](https://issues.redhat.com/browse/NETOBSERV-1105)
=> Moving cluster-density to cluster-density-v2

scripts/sandman.py
Want to be able to add a .sh file that we can export in our scripts instead of jq every variable every time 
Also adding a try except for if an error occurs inthe run and the end ouptut is not found for some reason, to find the last time regex (bug for reference: https://issues.redhat.com/browse/OCPQE-15860) CC: @SachinNinganure
=> Making sourcable file

Jenkinsfile
Can easily set env variables from build json
=> Adding buildInfo references

Jenkinsfile, scripts/README.md, scripts/deploy-loki-aws-secret.sh, scripts/netobserv.sh, scripts/nope.py
Based off convos with @paigerube14 
Also did some minor cleanup across our stack
=> More efficient parsing of Mr. Sandman output file

scripts/netobserv.sh
Tested here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/349/
=> Fix bug with S3 bucket naming

scripts/netobserv.sh
Test Jobs:
- https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/355
- https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/356
=> Minor script enhancements

scripts/sandman.py
Want to make all keys upper case instead of adding in to upper everywhere when reading dict. Also missed the i in iterations
=> Upper case and iterations typo

Jenkinsfile, write_to_sheet/write_scale_results_sheet.py
Adding network v2 to ignore uuid information
=> network perf v2

OWNERS
@paigerube14 Could you ptal? 
I just realized that some of my changes in PR https://github.com/openshift/release/pull/41599 were overwritten by auto-generated files using https://github.com/openshift/ci-tools. 
Ex: https://github.com/openshift/release/blob/master/ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/OWNERS and https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/OWNERS etc..
=> Updating OWNERS list per discussion with Paige.

Jenkinsfile
First run with no jenkinsfile errors: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/ingress-perf/2/console
=> adding ingress perf first commit

Jenkinsfile
Adding google sheet creation using benchmark-comparison job 
Passing job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner-ocp/55/console
=> Kube burner ocp google sheet creation

scripts/nope.py
Resolves [NETOBSERV-1237](https://issues.redhat.com/browse/NETOBSERV-1237)
=> Add performance baseline functionality to NOPE tool

Jenkinsfile
Properly calling ingress perf: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/loaded-upgrade/393/console
=> Adding ingress perf to loaded-upgrade

Jenkinsfile, post_uuid_to_es.py
Post results for ingress perf to es wiht baselines
=> Post results to es for ingress perf

scripts/sandman.py
Want to be able to continue finding variables in output file even when an error occurs. For the netobserv team they always want to fail the run if they have issues finding data points
=> Adding exit on failure option

Jenkinsfile
Found 2 files, want to delete current directory to verify only 1 file exists at a time
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/post-results-to-es/721/console
I can't really test this because I'm not sure when it happens
=> Delete dir 

write_to_sheet/write_scale_results_sheet.py
passing job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write-to_sheet/154/console
=> Adding ingress perf writing to file

Jenkinsfile, openshift-qe-move-pods-infra-commands.sh, openshift-qe-workers-infra-workload-commands.sh
Update code to exclude edge type machineset and adding more log in openshift-qe-move-pods-infra-commands.sh
Jenkins Logs:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/liqcui-e2e-benchmarking-multibranch-pipeline/job/cluster-post-config/233/console
=> Cluster post config

scripts/requirements.txt, scripts/sandman.py
Also did some whitespace cleanup
=> Added additional exception logging to Mr. Sandman

Jenkinsfile, configs/nodeAggWorkers-ocp.json, configs/nodeMasters-ocp.json, find_baseline_uuid.py, loop_rules2.sh, tolerancy-configs/master-tolerancy-ocp.yaml, tolerancy-configs/worker-agg-tolerancy-ocp.yaml, tolerancy-configs/worker-tolerancy-ocp.yaml, update_baseline_fields.py, update_es_uuid.py
Using cluster metadata to find uuid platform and data points
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/benchmark-comparison/219/console
=> Benchmark comparison

Jenkinsfile
https://issues.redhat.com/browse/OCPQE-16956
=> remove error from ingress-perf output check

Jenkinsfile
Taking out workloads that are now in kube-burner-ocp
=> taking out workloads that have moved

scripts/netobserv.sh, scripts/netobserv/flows_v1beta1_flowcollector.yaml
1.4 has some changes that requires tweaks to our Perf testing flowcollector CRD
=> Updates to flowcollector CRD

Jenkinsfile, helper_uuid.py, post_uuid_to_es.py, update_es_uuid.py
Update to only post baseline updates from post results to es job. Also adding platform to the results. This is necessary for the comparison 
Successful runs: 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/post-results-to-es/63/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/post-results-to-es/62/
=> Taking out post to elastic for non baseline data

Jenkinsfile
Find index file and make it as an artifact
=> adding get index file

scripts/nope.py
- Add additional configuration to Elasticsearch object initialization to cut down on potential errors hit if there is network trouble during large uploads
- Modified `run_commands` as AWS commands were still failing the tool when they shouldn't have been
=> NOPE tool enhancements

Jenkinsfile, requirements.txt, write_to_sheet/get_es_data.py, write_to_sheet/prow_write.py, write_to_sheet/update_es_uuid.py, write_to_sheet/write_helper.py, write_to_sheet/write_scale_results_sheet.py
Want to write google sheet results using data gotten from outputted file in e2e-benchmark 
Need to still test with network-perf-v2 and ingress
=> Write to sheet with reading index data file 

Jenkinsfile
Adding back correct grep files, with Qiujie's comment in: https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/530
=> Ingress perf

Jenkinsfile, scripts/netobserv.sh, scripts/netobserv/netobserv-dittybopper.yaml.template, scripts/nope.py
Tested here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/415/
=> Fixed downstream detection and upstream Dittybopper

write_to_sheet/update_es_uuid.py, write_to_sheet/write_scale_results_sheet.py
Need to extend the request timeout of getting results from elastic search. May have to up this even more but increasing to 40 seconds as a start
=> Write to sheet extend request timeout

Jenkinsfile
The same as https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/547
=> Fix agent issue

Jenkinsfile
Properly calling comparison job here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/ingress-perf/23/console
=> Ingress perf with comparison

scripts/netobserv/flows_v1beta2_flowcollector.yaml
To align with further `v1beta2` changes
=> Changed ignoreTags to includeList

Jenkinsfile
Fixing bug introduced in https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/552
Job fails if no patching is done due to how variables are handled, see https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/448/console
This moves the patch check into the `if` block itself
=> Fixed bug with image patching

scripts/netobserv/flows_v1beta2_flowcollector.yaml
Need to update our flowcollector CRD here for compatability
=> Flowcollector PascalCase updates

Jenkinsfile
=> New changes for benchmark-comparison 

Jenkinsfile
Scale up rhel nodes in loaded-upgrade
Passing job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/loaded-upgrade/417/console
=> Adding rhel scale up

Jenkinsfile
Missed taking out some variables that i took out in last PR 
Error seen here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/loaded-upgrade/420/console
Got past that error here (but hit flexy issue) https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/loaded-upgrade/421/console
=> Loaded upgrade

scripts/netobserv.sh
Successfully tested here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/465/
=> Change 'KAFKA' to 'Kafka' to align with flowcollector API change

scripts/queries/netobserv_touchstone_tolerancy_rules.yaml
Based on our conversation in Sync
=> Updated how we tolerate nFlowsProcessedPerMinuteTotals

Jenkinsfile, scripts/README.md, scripts/nope.py
Resolves [NETOBSERV-1290](https://issues.redhat.com/browse/NETOBSERV-1290)
=> Added ingress-perf workload functionality

Jenkinsfile
Related to https://github.com/cloud-bulldozer/e2e-benchmarking/pull/669
=> Add index_data.json to artifacts collection

Jenkinsfile
Need to update to the new krkn-chaos org/repo: https://github.com/krkn-chaos/krkn-hub
All jobs will fail, need it in for any job to pass
=> Krkn hub updates for cerberus

Jenkinsfile
Create google sheet creation only if csv gets created
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/benchmark-comparison/296/console
=> Benchmark comparison google sheet creation

Jenkinsfile
want to archive the json details file if script fails, currently wont get to that step
=> Adding archive even if script fails

scripts/netobserv/flows_v1beta2_flowcollector.yaml
=> NETOBSERV-1092 flowcollector CRD changes

Jenkinsfile
Passing job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner-ocp/102/
=> Adding profile type 

Jenkinsfile, scripts/catalogsources/netobserv-downstream-testing.yaml, scripts/catalogsources/netobserv-main-catalogsource.yaml, scripts/catalogsources/netobserv-upstream-testing.yaml, scripts/catalogsources/qe-unreleased-catalogsource.yaml, scripts/loki/loki-unreleased-subscription.yaml, scripts/netobserv.sh, scripts/netobserv/netobserv-internal-subscription.yaml, scripts/netobserv/netobserv-source-subscription.yaml, scripts/nope.py, scripts/queries/netobserv_dittybopper.json, scripts/queries/netobserv_prometheus_queries.yaml, scripts/queries/netobserv_touchstone_statistics_config.json, scripts/queries/netobserv_touchstone_tolerancy_config.json, scripts/queries/netobserv_touchstone_tolerancy_rules.yaml
Part of [NETOBSERV-1543](https://issues.redhat.com/browse/NETOBSERV-1543)
Also a few other tweaks:
- Additional logging for the NOPE tool
- Adds Unified Agent support by replacing FLP daemonset check with eBPF daemonset check (resolves [NETOBSERV-1515](https://issues.redhat.com/browse/NETOBSERV-1515))
- Added support for LokiStack `1x.demo` size in Jenkins
- Updated and renamed custom CatalogSources
=> Updates to Prometheus metrics and Touchstone configs

prow/README.md, prow/get_periodic_jobs.py
Storing periodic job generation document in prow folder
=> Periodic job - gsheet generation

prow/generate_jobs_in_gsheet/get_periodic_jobs.py, prow/generate_jobs_in_gsheet/requirements.txt
Prepare work for https://issues.redhat.com/browse/PERFSCALE-2954
- Add code for cron that is not in normal cron format like '@yearly'
- Add requirements.txt
- Get Google sheet secret from 'GSHEET_KEY_LOCATION' env variable
- Add ability to change GSHEET_LOCATION and JOBS_FOLDER_LOCATION
=> refine get_periodic_jobs.py

scripts/queries/netobserv_touchstone_tolerancy_config.json, scripts/queries/netobserv_touchstone_tolerancy_rules.yaml
Part of [NETOBSERV-1543](https://issues.redhat.com/browse/NETOBSERV-1543)
=> Add workload flow statistics to comparison

scripts/nope.py
This changes the `--dump` json format to include the `raw_data` in `data` along with the `metric_name` and `query` that produced the `raw_data`. This also moves the `jenkins_env` and `netobserv_env` objects outside the `RESULST['data']` array to simplify processing when converting to `clean_data` for elastic search upload.
The goal of this change is to persist the data from the System Under Test (SUT) in a format that closely matches the format from the underlying tools (e.g. prometheus). This format will help support other tools' use of the data and decrease the json document size by decreasing the number of copies of the `metric` prometheus response field that is currently persisted in the `metadata` field. 
Note: Please check the PR as though it was written by a 5-year-old. I do not …
=> change dump format to include raw_data

OWNERS
Can still review PRs of course, but need to cut down on my GitHub notifications
=> Remove Nathan from automatic GitHub reviewers

prow/generate_jobs_in_gsheet/get_periodic_jobs.py
Couldn't find release in file https://github.com/openshift/release/blob/master/ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__write_jobs_to_gsheet.yaml that is being looked at in the job
=> Adding if statement for blank release

Jenkinsfile, scripts/netobserv.sh, scripts/netobserv/flows_v1beta2_flowcollector.yaml
* NETOBSERV-1677 updates for parameters and ability option to disable loki
* This is also refactor of Jenkinsfile stage `Configure NetObserv, flowcollector, and Kafka` and netobserv.sh script to use flowcollector template instead of yaml file - should help to simplify it. 
* use flowcollector template, refactoring and adding more params
* add 1x.demo
=> NETOBSERV-1677 - updates

scripts/README.md, scripts/netobserv.sh, scripts/netobserv/flows_v1beta2_flowcollector.yaml, scripts/queries/netobserv_prometheus_queries.yaml, scripts/queries/netobserv_touchstone_statistics_config.json, scripts/queries/netobserv_touchstone_tolerancy_config.json
ebpf metrics, enabling FLP metrics and fixing kafkaTopic delete issue
=> NETOBSERV-1694 metrics and fixing kafkaTopic delete issue

Jenkinsfile, scripts/netobserv.sh
Successful run with artifacts: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/memodi-e2e-benchmarking-multibranch-pipeline/job/artifacts/9/
=> archive artifacts

scripts/netobserv/flows_v1beta2_flowcollector.yaml
=> flp loglevel to info

prow/Dockerfile
=> Adding rhel8 oc

Jenkinsfile
=> FLP kafka replicas bug fix

Jenkinsfile, scripts/nope.py, scripts/queries/netobserv_prometheus_queries.yaml, scripts/queries/netobserv_touchstone_statistics_config.json, scripts/queries/netobserv_touchstone_tolerancy_config.json, scripts/queries/netobserv_touchstone_tolerancy_rules.yaml, scripts/sheets/es_search.py, scripts/sheets/noo_perfsheets_update.py, scripts/sheets/requirements.txt, scripts/sheets/sheets.py
- Add NOO Bundle info to replace UUID for comparison perf sheet
Examples:
-  [sheet](https://docs.google.com/spreadsheets/d/1CQvUg3CJbPdhSCX__u_-Kw62F5zld3vrKH75BhsazaQ/edit?gid=949491585#gid=949491585) When using Downstream QE index catalog image. 
- When pre-merge Operator bundle image is used, that value will be used in sheets:
=> NETOBSERV-1709 update noo comparison sheets with context

Jenkinsfile, kraken.sh, set_kraken_files.sh
- kube config location changes
- Start on getting hog scenarios working still work in progress
- new krkn-chaos github org as default in parameters
=> Kraken Updates

Jenkinsfile, set_kraken_files.sh
Passing jobs: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kraken/167/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kraken/168/
=> Kraken more updates 

prow/Dockerfile_test
Need a base dockerfile without oc. The oc will be installed in the image in prow
=> Adding test dockerfile

scripts/queries/netobserv_prometheus_queries.yaml, scripts/queries/netobserv_touchstone_statistics_config.json, scripts/queries/netobserv_touchstone_tolerancy_config.json, scripts/queries/netobserv_touchstone_tolerancy_rules.yaml
[NETOBSERV-1715](https://issues.redhat.com//browse/NETOBSERV-1715) network in/out metrics
=> NETOBSERV-1715 network in/out metrics

scripts/nope.py, scripts/sheets/noo_perfsheets_update.py
Sample sheet: https://docs.google.com/spreadsheets/d/1wvjKnI0T6CSybnrpJeCpDAIM7uefbmF5PvytyfUb8ds/edit?gid=1384501499#gid=1384501499
=> add datetime context

Jenkinsfile, set_kraken_files.sh
Link to the kraken run - 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/shyadav-e2e-benchmarking-multibranch-pipeline/job/kraken/48/
=> Changes in Jenkins file

Jenkinsfile
Automate/Fix the 'port_allow' issue of aws-ocp in the Jenkins for the k8s netperf tests
=> add allow-port stage

Jenkinsfile
Got past earlier failures here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cluster-builder/10/console
Failing job from cluster-builder: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Flexy-install/306525/parameters/
=> Cluster builder

Jenkinsfile
Had duplicate profiles, need in asap
=> Duplicate profile type

Jenkinsfile, scripts/build_info.sh, scripts/run_py_scripts.sh
[NETOBSERV-1791](https://issues.redhat.com//browse/NETOBSERV-1791) Refactor pipeline to be smaller size and also cleaner by moving scripts as functions in separate scripts.
Success run: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/memodi-e2e-benchmarking-multibranch-pipeline/job/refactor-pipeline/37/
=> NETOBSERV-1791 Refactor pipeline to be smaller size

.gitignore, prow/generate_jobs_in_gsheet/get_periodic_jobs.py
Need to add if statement for any possible missing keys
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-write_jobs_to_gsheet-write-jobs-to-google-sheet-sprintly/1840904914549608448
=> Adding env if statement

prow/generate_jobs_in_gsheet/get_periodic_jobs.py
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-write_jobs_to_gsheet-write-jobs-to-google-sheet-sprintly/1841878184342065152
=> Adding one more if statement

prow/generate_jobs_in_gsheet/get_periodic_jobs.py
Ran locally with new edits and it created tab **ProwCadence10/17/2024-092329** in the google sheet
=> Adding profile type

Jenkinsfile
- [NETOBSERV-1962](https://issues.redhat.com/browse/NETOBSERV-1962) Run ingress-perf in parallel with NDH and CD workloads
- [NETOBSERV-1963](https://issues.redhat.com/browse/NETOBSERV-1963) Enable kube-burner-ocp Churn option for node-density-heavy and cluster-density-v2 workloads -- currently Churn option is only enabled for cluster-density workloads. For NDH, it's dependent on the PR: https://github.com/kube-burner/kube-burner-ocp/pull/93
- Option to run ingress-perf in parallel (Default: true).  When unchecked we would be able to run NDH and CD-v2 as standalone.
- Option to run ingress-perf workload as standalone.
=> NETOBSERV-1962 Run ingress-perf in parallel with NDH and CD workloads

Jenkinsfile
Last PR introduced a bug where NOO_BUNDLE_VERSION is not captured properly, this PR fixes both cases when Installation method is None or otherwise, NOO_BUNDLE_VERSION will be left null or updated.
=> bug fix to update NOO_BUNDLE_VERSION

Jenkinsfile, loop_rules.sh, loop_rules2.sh
Generated link is not working anymore - opening not existing dashboard,
Update to current one.
=> Update grafana dashboard link

get_graphana_link.py
I missed this one link - the most important right now :)
=> Correct link to report - missed one

scripts/netobserv/flows_v1beta2_flowcollector.yaml
add flowfilter and fix features spec
=> add flowfilter and fix features spec

Jenkinsfile
Switch new agent
Jenkins Jobs:
https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/scale-ci/job/liqcui-e2e-benchmarking-multibranch-pipeline/job/kube-burner/931/console
=> switch new agent

scripts/netobserv.sh, scripts/nope.py
update jenkins URL and loki cleanup fix
=> update jenkins URL and loki cleanup fix

scripts/env.sh, scripts/netobserv.sh, scripts/queries/netobserv_dittybopper.json
Fixes for clean up and dashboard now includes Flow Error panels
=> Fixes for clean up and dashboard updates

scripts/netobserv/flows_v1beta2_flowcollector.yaml
- Add PacketTranslation to feature list
- Also remove writeBatchSize since [NETOBSERV-1766](https://issues.redhat.com/browse/NETOBSERV-1766) is fixed
=> Add PacketTranslation feature

Jenkinsfile, scripts/env.sh, scripts/loki/loki-subscription.yaml, scripts/loki/lokistack.yaml, scripts/netobserv.sh, scripts/netobserv/netobserv-subscription.yaml
- Template fixes for Namespace
- disable must-gather
- add waitForResources func
=> Template fixes for Namespace and disable must-gather

scripts/netobserv.sh
=> add break in while loop

Jenkinsfile
update agent for storage csi job
=> update agent for storage csi job

scripts/netobserv.sh
$ARTIFACT_DIR is set by Prow CI for artifacts to be archived.
=> NETOBSERV-2128 add artifacts dir to be used in prow ci

scripts/amq-streams/default.yaml, scripts/amq-streams/metrics-config.yaml, scripts/netobserv.sh, scripts/nope.py
Dependent on https://github.com/netobserv/documents/pull/83
=> Get rid of infinite loops, exit and use tmp in nope.py

Jenkinsfile, scripts/nope.py
use ISO timestamps and set warning loglevel for es
=> use ISO timestamps and set warning loglevel for es

scaling.sh
update code to use full name for machines and machineset
The Jenkins job:
https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/scale-ci/job/liqcui-e2e-benchmarking-multibranch-pipeline/job/cluster-workers-scaling/968/console
=> update code to use full name for machines and machineset

Jenkinsfile, scripts/netobserv/flows_v1beta2_flowcollector.yaml
Changes:
- Add UDN feature to flowcollector
- Remove IIB override config
=> Add UDN feature to flowcollector

OWNERS
Add netobserv team to OWNERS for netobserv perf jobs
=> Add netobserv team to OWNERS

scripts/build_info.sh, scripts/netobserv.sh
=> fix build_info.sh

Jenkinsfile
https://issues.redhat.com/browse/OCPQE-29960
=> add ES credentials to regression Jenkins

Jenkinsfile, README.md
https://issues.redhat.com/browse/OCPQE-29985
=> Bump default value of JENKINS_AGENT_LABEL for benchmark-cleaner branch

Jenkinsfile, scripts/amq-streams/default.yaml, scripts/amq-streams/metrics-config.yaml, scripts/amq-streams/nodePool.yaml, scripts/netobserv.sh
Add KafkaNodePool configs for NetObserv
=> NETOBSERV-2353: KafkaNodePool configs

OWNERS, scripts/README.md, scripts/queries/netobserv-orion-cluster-density-v2-ospst.yaml, scripts/queries/netobserv-orion-cluster-density-v2.yaml, scripts/queries/netobserv-orion-node-density-heavy-ospst.yaml, scripts/queries/netobserv-orion-node-density-heavy-pull.yaml, scripts/queries/netobserv-orion-node-density-heavy.yaml, scripts/queries/netobserv_prometheus_queries.yaml
- Update orion configs for version to be specific, remove index configs and update readme.
- fix for flpMetricsCardinality
- add Oliver
=> Update orion configs for version and fix for flpMetricsCardinality

scripts/queries/netobserv-orion-cluster-density-v2-ospst.yaml, scripts/queries/netobserv-orion-cluster-density-v2.yaml, scripts/queries/netobserv-orion-node-density-heavy-ospst.yaml, scripts/queries/netobserv-orion-node-density-heavy-pull.yaml, scripts/queries/netobserv-orion-node-density-heavy.yaml
add quote around version variable
=> add quote around version variable

scripts/deploy-loki-aws-secret.sh, scripts/loki/lokistack.yaml, scripts/netobserv.sh, scripts/netobserv/flows_v1beta2_flowcollector.yaml, scripts/queries/netobserv_prometheus_queries.yaml
[NETOBSERV-2404](https://issues.redhat.com//browse/NETOBSERV-2404) use loki and kafka in dedicated NS
=> NETOBSERV-2404 use loki and kafka in dedicated NS

scripts/netobserv.sh
Need to deploy netobserv NS for [netobserv.sh#L283](https://github.com/openshift-eng/ocp-qe-perfscale-ci/blob/netobserv-perf-tests/scripts/netobserv.sh#L283)
=> NETOBSERV-2404: Deploy netobserv NS

scripts/orion/ack.yaml
Adding ack file for Orion to acknowledge known issues so subsequent runs can succeed: 
https://github.com/cloud-bulldozer/orion/blob/main/docs/usage.md#acknowledging-known-issues
=> Add ack file for Orion
